{
 "title": "DARKTRACE EVENTS AND ALERTS",
 "description": "DARKTRACE - SUMMARY",
 "tags": [ "DARKTRACE" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters", "label": "Filters" },
   {
    "name": "source",
    "label": "Source",
    "query": "{ \"find\": \"terms\", \"field\": \"source\", \"query\": \"*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "model_now_actions_alert:true AND source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SENSORS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "source",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY SENSOR",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "model_now_actions_alert:true AND source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY CATEGORY",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "model_now_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "model_now_actions_alert:true AND source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DEVICES - TOTAL",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "device_hostname", "id": "1", "type": "cardinality" }
     ],
     "query": "source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY DEVICE",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "device_hostname",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DEVICES BY OS",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "device_os",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS - TOTAL",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY SENSOR - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "source:$source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}