/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardActions: typeof import('./src/components/cards/CardActions.vue')['default']
    CardBasic1: typeof import('./src/components/cards/basic/CardBasic1.vue')['default']
    CardBasic2: typeof import('./src/components/cards/basic/CardBasic2.vue')['default']
    CardBasic3: typeof import('./src/components/cards/basic/CardBasic3.vue')['default']
    CardBasic4: typeof import('./src/components/cards/basic/CardBasic4.vue')['default']
    CardBasic5: typeof import('./src/components/cards/basic/CardBasic5.vue')['default']
    CardBasic6: typeof import('./src/components/cards/basic/CardBasic6.vue')['default']
    CardCodeExample: typeof import('./src/components/cards/CardCodeExample.vue')['default']
    CardCombo1: typeof import('./src/components/cards/combo/CardCombo1.vue')['default']
    CardCombo2: typeof import('./src/components/cards/combo/CardCombo2.vue')['default']
    CardCombo3: typeof import('./src/components/cards/combo/CardCombo3.vue')['default']
    CardCombo4: typeof import('./src/components/cards/combo/CardCombo4.vue')['default']
    CardCombo5: typeof import('./src/components/cards/combo/CardCombo5.vue')['default']
    CardCombo6: typeof import('./src/components/cards/combo/CardCombo6.vue')['default']
    CardCombo7: typeof import('./src/components/cards/combo/CardCombo7.vue')['default']
    CardCombo8: typeof import('./src/components/cards/combo/CardCombo8.vue')['default']
    CardComboIcon: typeof import('./src/components/cards/combo/CardComboIcon.vue')['default']
    CardEcommerce1: typeof import('./src/components/cards/ecommerce/CardEcommerce1.vue')['default']
    CardEcommerce2: typeof import('./src/components/cards/ecommerce/CardEcommerce2.vue')['default']
    CardEcommerce3: typeof import('./src/components/cards/ecommerce/CardEcommerce3.vue')['default']
    CardEcommerce4: typeof import('./src/components/cards/ecommerce/CardEcommerce4.vue')['default']
    CardExtra1: typeof import('./src/components/cards/extra/CardExtra1.vue')['default']
    CardExtra2: typeof import('./src/components/cards/extra/CardExtra2.vue')['default']
    CardExtra3: typeof import('./src/components/cards/extra/CardExtra3.vue')['default']
    CardExtra4: typeof import('./src/components/cards/extra/CardExtra4.vue')['default']
    CardExtra5: typeof import('./src/components/cards/extra/CardExtra5.vue')['default']
    CardExtra6: typeof import('./src/components/cards/extra/CardExtra6.vue')['default']
    CardExtra7: typeof import('./src/components/cards/extra/CardExtra7.vue')['default']
    CardSocial1: typeof import('./src/components/cards/social/CardSocial1.vue')['default']
    CardWrapper: typeof import('./src/components/cards/CardWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
