minimumReleaseAge: 0

trustPolicy: off
trustPolicyExclude:
  - chokidar
  - semver

peerDependencyRules:
  allowedVersions:
    eslint: "10"

shellEmulator: true

overrides:
  rolldown: 1.0.1

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
