{
 "title": "HUNTRESS - _SUMMARY",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "EVENTS - CRITICAL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:critical",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS - CRITICAL (SOURCE)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:critical",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS - CRITICAL (SUBJECT)",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "subject",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:critical",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY AGENT - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY PLATRFORM",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "platform",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY SEVERITY",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "severity",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY SEVERITY - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "severity",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY INDICATOR TYPES",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "indicator_types",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}