from .agents import router as agents_router
from .auth import router as auth_router
from .connectors import router as connectors_router
from .cortex import router as cortex_router
from .customers import router as customers_router
from .dfir_iris import router as dfir_iris_router
from .dnstwist import router as dnstwist_router
from .graylog import router as graylog_router
from .healthcheck import router as healtcheck_router
from .logs import router as logs_router
from .shuffle import router as shuffle_router
from .smtp import router as smtp_router
from .sublime import router as sublime_router
from .velociraptor import router as velociraptor_router
from .wazuh_indexer import router as wazuh_indexer_router
from .wazuh_manager import router as wazuh_manager_router
