"""The write operations a Customer Portal user (``customer_user``) may perform are pinned.

Every route that admits ``customer_user`` is tenant-checked, but that only stops a
customer from touching *another* tenant's data. What a customer may do to *their
own* SOC record is a separate, product-level decision: an end customer can triage
alerts and cases, comment, open cases, upload files and generate reports, but must
not delete alerts, cases or case files, escalate, move a case to another customer
or fire Shuffle workflows. Those remain analyst actions.

This test enumerates every non-GET route whose scope dependency admits
``customer_user`` and compares it with ``ALLOWED_CUSTOMER_USER_WRITES``. Adding
``customer_user`` to a write route, or removing it from one, fails here until the
allowlist is updated — which is the point: the change has to be deliberate.

Run with: cd backend && python -m pytest tests/test_customer_user_write_allowlist.py
"""

import inspect
import os

os.environ.setdefault("JWT_SECRET", "test-only-secret-not-the-compromised-default")

from fastapi.routing import APIRoute  # noqa: E402

CUSTOMER_USER = "customer_user"
READ_METHODS = {"GET", "HEAD", "OPTIONS"}

ALLOWED_CUSTOMER_USER_WRITES = frozenset(
    {
        # Own account: password and 2FA self-service.
        ("POST", "/api/auth/reset-password/me"),
        ("POST", "/api/auth/2fa/setup"),
        ("POST", "/api/auth/2fa/verify-setup"),
        ("POST", "/api/auth/2fa/backup-codes/regenerate"),
        ("DELETE", "/api/auth/2fa/disable"),
        # Alert triage.
        ("PUT", "/api/incidents/db_operations/alert/status"),
        ("PUT", "/api/incidents/db_operations/alerts/status"),  # bulk form of the above (#1098)
        ("POST", "/api/incidents/db_operations/alert/comment"),
        ("PUT", "/api/incidents/db_operations/alert/comment"),
        ("DELETE", "/api/incidents/db_operations/alert/comment/{comment_id}"),
        # Case management.
        ("POST", "/api/incidents/db_operations/case/create"),
        ("POST", "/api/incidents/db_operations/case/from-alert"),
        ("PUT", "/api/incidents/db_operations/case/status"),
        ("PUT", "/api/incidents/db_operations/case/assigned-to"),
        ("POST", "/api/incidents/db_operations/case/alert-link"),
        ("POST", "/api/incidents/db_operations/case/alert-unlink"),
        ("POST", "/api/incidents/db_operations/case/comment"),
        ("PUT", "/api/incidents/db_operations/case/comment"),
        ("DELETE", "/api/incidents/db_operations/case/comment/{comment_id}"),
        ("POST", "/api/incidents/db_operations/case/data-store/upload"),
        # Reports: generated by the customer, and regenerable, so deleting one loses no evidence.
        ("POST", "/api/incidents/customer_reports/generate/background"),
        ("DELETE", "/api/incidents/customer_reports/{report_id}"),
        # Asset criticality of the customer's own agents.
        ("POST", "/api/agents/{agent_id}/critical"),
        ("POST", "/api/agents/{agent_id}/noncritical"),
        # Reads that take a body, so they are POSTs. They change nothing.
        ("POST", "/api/siem/dashboards/panel-data"),
        ("POST", "/api/copilot_searches/by-ids"),
        ("POST", "/api/copilot_searches/provision/graylog/check"),
        ("POST", "/api/copilot_searches/catalog/wazuh-rules/test"),
    },
)

# Kept here so the intent survives a future edit of the allowlist above.
ANALYST_ONLY_WRITES = frozenset(
    {
        ("DELETE", "/api/incidents/db_operations/alert/{alert_id}"),
        ("DELETE", "/api/incidents/db_operations/alerts/by-title/{title_filter}"),
        ("PUT", "/api/incidents/db_operations/alert/escalated"),
        ("DELETE", "/api/incidents/db_operations/case/{case_id}"),
        ("DELETE", "/api/incidents/db_operations/case/data-store/{case_id}/{file_name}"),
        ("PUT", "/api/incidents/db_operations/case/escalated"),
        ("PUT", "/api/incidents/db_operations/case/customer-code"),
        ("POST", "/api/incidents/db_operations/case/notification"),
        ("POST", "/api/copilot_searches/refresh"),
    },
)


def _required_scopes(call) -> set:
    """The scopes captured by an ``AuthHandler().require_any_scope(...)`` dependency, if ``call`` is one."""
    try:
        scopes = inspect.getclosurevars(call).nonlocals.get("required_scopes")
    except TypeError:
        return set()
    return set(scopes) if isinstance(scopes, tuple) else set()


def _route_scopes(dependant) -> set:
    scopes = set()
    for dependency in dependant.dependencies:
        if dependency.call is not None:
            scopes |= _required_scopes(dependency.call)
        scopes |= _route_scopes(dependency)
    return scopes


def _customer_user_routes():
    import copilot

    routes = set()
    for route in copilot.app.routes:
        if isinstance(route, APIRoute) and CUSTOMER_USER in _route_scopes(route.dependant):
            routes |= {(method, route.path) for method in route.methods}
    return routes


def test_scope_extraction_sees_customer_user_routes():
    # Guards against a vacuous pass if the introspection ever stops finding scopes.
    assert ("GET", "/api/incidents/db_operations/alerts") in _customer_user_routes()


def test_customer_user_writes_match_the_allowlist():
    writes = {(method, path) for method, path in _customer_user_routes() if method not in READ_METHODS}

    unexpected = sorted(writes - ALLOWED_CUSTOMER_USER_WRITES)
    missing = sorted(ALLOWED_CUSTOMER_USER_WRITES - writes)
    assert not unexpected, f"customer_user can reach write routes outside the allowlist: {unexpected}"
    assert not missing, f"allowlisted write routes no longer admit customer_user (update the allowlist): {missing}"


def test_evidence_and_workflow_writes_stay_analyst_only():
    assert not ALLOWED_CUSTOMER_USER_WRITES & ANALYST_ONLY_WRITES
    assert not _customer_user_routes() & ANALYST_ONLY_WRITES
