{
 "title": "EDR - NETWORK CONNECTIONS",
 "tags": [ "EDR" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"(rule_group3:sysmon_event3 OR rule_group2:misp_alert OR rule_group2:packetbeat) AND (data_win_eventdata_destinationIsIpv6:false OR data_eventdata_destinationIsIpv6:false OR data_event_category:\\\"network_traffic, network\\\")\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "FLAGGED IPs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND ((rule_group2:opencti AND data_opencti_entity_type:IPv4-Addr) OR (_exists_:misp_category AND misp_type:ip-dst))",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FLAGGED DST IPs / AGENT",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:140",
       "fake": true,
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:138", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND ((rule_group2:opencti AND data_opencti_entity_type:IPv4-Addr) OR (_exists_:misp_category AND misp_type:ip-dst OR misp_type:\"ip-dst|port\"))",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FLAGGED IPs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "misp_value",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:misp_category AND (misp_type:ip-dst OR misp_type:\"ip-dst|port\")",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data_opencti_value",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_group2:opencti AND agent_name:$agent_name AND data_opencti_entity_type:IPv4-Addr",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NETWORK EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:473",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:471", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 DST IPs",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst_ip",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "type",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CONNECTIONS MAP (TOP 10 IPs)",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "dst_ip",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "dst_port",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name AND (data_eventdata_sourceIsIpv6:false OR data_win_eventdata_sourceIsIpv6:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 AGENTS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DST GEOIP",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 27 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst_ip_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 PROCESSES - NETWORK CONNS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "process_image",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "type",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "rule_group3:sysmon_event3 AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "PROCESSES - NETWORK CONNS",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:167",
       "fake": true,
       "field": "process_image",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:165",
       "field": "type",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "rule_group3:sysmon_event3 AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LEAST SEEN PROCESSES - NETWORK CONNS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "process_image",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "type",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "rule_group3:sysmon_event3 AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NETWORK CONNS - TOP 10 USER ACCOUNTS",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:378",
       "fake": true,
       "field": "user_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:379",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:376", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_group3:sysmon_event3 AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NETWORK CONNS - USER / ACCOUNT",
   "type": "table",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 52 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:327",
       "fake": true,
       "field": "user_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:325", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_group3:sysmon_event3 AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NETWORK CONNS",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      { "type": "date_histogram", "id": "1", "settings": { "interval": "auto" } }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "(rule_group3:sysmon_event3 OR rule_group2:packetbeat) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}