{
 "title": "EDR - FILE INTEGRITY MONITORING",
 "tags": [ "EDR" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_level\", \"query\": \"(rule_group2:syscheck OR rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_15 OR rule_group3:sysmon_event_13)\"}"
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FIM - IoCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level AND _exists_:threat_intel_type",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IoCs BY TYPE AND SEVERITY",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3082",
       "fake": true,
       "field": "rule_groups",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "syslog_level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "misp_value",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level AND _exists_:threat_intel_type",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FIM - EVENTS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SEVERITY LEVELS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "rule_level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:74",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY TYPE AND SEVERITY",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3082",
       "fake": true,
       "field": "rule_groups",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "rule_level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY AGENT (HISTOGRAM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS SUMMARY",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "(rule_group3:sysmon_event_11 OR rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_group3:sysmon_event_15 OR rule_group2:syscheck) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "WINDOWS REGISTRY INTEGRITY MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 35 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY SEVERITY",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 35 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_groups",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY USER ACCT (Top 100)",
     "type": "table",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 42 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "data_win_eventdata_user",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY REGISTRY OBJECT (Top 100)",
     "type": "table",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 42 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "data_win_eventdata_targetObject",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "syscheck_path",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS REGISTRY EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "(rule_group3:sysmon_event_12 OR rule_group3:sysmon_event_13 OR rule_groups:*syscheck_registry) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FILE INTEGRITY MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIM - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FIM -  EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 36 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FIM - EVENTS BY SEVERITY",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY RULE GROUPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 36 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_groups",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY USER ACCT (Top 100)",
     "type": "table",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 43 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "data_win_eventdata_user",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY FILE PATH (Top 100)",
     "type": "table",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 43 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "target_file",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FIM - EVENTS",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "(rule_group3:sysmon_event_11 OR rule_groups:*syscheck_file) AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "WINDOWS REMOTE THREAD EVENTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "REMOTE THREADS - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_group3:sysmon_event_15 AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 37 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_group3:sysmon_event_15 AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY SEVERITY",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_group3:sysmon_event_15 AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY USER ACCOUNT",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 37 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:2063",
         "fake": true,
         "field": "data_win_eventdata_user",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_group3:sysmon_event_15 AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS BY PROCESS AND SEVERITY",
     "type": "table",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 44 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "process_image",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_group3:sysmon_event_15 AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EVENTS",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule_group3:sysmon_event_15 AND rule_level:$rule_level",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}