{
 "title": "EDR - AGENT INVENTORY",
 "tags": [ "EDR" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"rule_groups:*inventory\"}"
   }
  ]
 },
 "panels": [
  { "title": "AGENTS INVENTORY - SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "INVENTORY ITEMS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:*inventory",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "INVENTORY ITEMS BY MODULE",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "data_inventory_module",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:74",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:*inventory",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "INVENTORY ITEMS BY MODULE",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "data_inventory_module",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:*inventory",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "INVENTORY ITEMS BY AGENT",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3082",
       "fake": true,
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:*inventory",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "PENDING RESTARTS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND data_restart_pending:True",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "RESTARTS PENDING - AGENTS",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND data_restart_pending:True",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SERVICES STOPPED",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND data_service_start_mode:Auto AND data_service_state:Stopped",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "STOPPED SERVICES",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "data_service_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND data_service_start_mode:Auto AND data_service_state:Stopped",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS BY OS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "agent_name:$agent_name AND (data_inventory_module:operating_system)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - SYSTEM INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HARDWARE MANUFACTURERS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_manufacturer",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:computer_info",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "HARDWARE MODELS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_model",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:computer_info",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 10, "y": 28 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:computer_info",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "UEFI",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data_uefi_enabled",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:uefi",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "AGENTS BY NBR OF PROCESSORS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_processor_cores",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:processor",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "PROCESSORS INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 36 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:processor",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "BIOS INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:bios",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "PENDING RESTARTS",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_restart_pending:True",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "RESTARTS PENDING - AGENTS",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_restart_pending:True",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM DRIVES",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:drives",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "BITLOCKER",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:bitlocker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SECURE BOOT",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:partitions",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - OS INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "AGENTS BY OS TYPE",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_os_type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:*inventory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "AGENTS BY OS TYPE",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 5, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_os_type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:*inventory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "BOOT TIME",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data_os_boot_time",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:*inventory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OS INVENTORY",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:operating_system",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - PRINTERS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "INSTALLED PRINTERS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:printers",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - IPv4 INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "NIC AND IPv4",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:nic",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "IPv4 ROUTE TABLE",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:route_table",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - INSTALLED SOFWARE AND HOTFIXES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "INSTALLED SOFTWARE - TOTAL",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "data_software_name", "id": "1", "type": "cardinality" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:software",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "INSTALLED SOFTWARE BY VENDOR",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_software_vendor",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:software",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "INSTALLED SOFTWARE BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 32 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:software",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SOFTWARE INVENTORY",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:software",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS HOTFIXES",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:hotfix",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - SHARED DRIVES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "DRIVE SHARES",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:shares",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - SYSTEM SERVICES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL SYSTEM SERVICES",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "data_service_name", "id": "1", "type": "cardinality" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:system_services",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM SERVICES BY STATE",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_service_state",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:system_services",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM SERVICES BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 34 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:system_services",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM SERVICES INVENTORY",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:system_services",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - LOCAL USER ACCOUNTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOCAL ACCOUNTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:local_user_accounts",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "WINDOWS DEFENDER SETTINGS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "REAL TIME DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_disable_real_time_monitoring:true ",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NETWORK PROTECTION DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_enable_network_protection:0",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "UI ACCESS ENABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_ui_lockdown:false",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "REMOVABLE MEDIA SCAN DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_disable_removable_drive_scanning:true",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SCRIPTS SCAN DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_disable_script_scanning:true",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "BEHAVIOR MONITORING DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_disable_behavior_monitoring:true",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DEFENDER - MAIN SETTINGS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:windows_defender",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NETWORK FILES SCAN DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_disable_network_files_scan:true ",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CONTROLLED FOLDER ACCESS DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_enable_control_folder_access:0",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EXTENSIONS EXCLUSION DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_exclusion_extension:null",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SAMPLES SUBMITTED FOR ANALYSIS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_submit_samples_content:1",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FILES EXCLUSION DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_exclusion_path:null",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DEFENDER AV - EXCLUDED PATHS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 4, "y": 32 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "data_exclusion_path",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "agent_name:$agent_name AND data_exclusion_path<>null",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "PROCESS EXCLUSION DISABLED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND data_exclusion_process:null",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DEFENDER AV - EXCLUDED PROCESSES",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 4, "y": 38 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "data_exclusion_process",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "agent_name:$agent_name AND data_exclusion_process:<>null",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DEFENDER - ALL SETTINGS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND data_inventory_module:windows_defender",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}