{
 "title": "EDR - OPEN AUDIT",
 "tags": [ "EDR" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"rule_groups:open-audit\"}"
   }
  ]
 },
 "panels": [
  { "title": "AGENTS INVENTORY - SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "INVENTORY ITEMS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:open-audit",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "INVENTORY ITEMS BY MODULE",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "rule_description",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:74",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:open-audit",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "INVENTORY ITEMS BY MODULE",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "rule_description",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:open-audit",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "INVENTORY ITEMS BY AGENT",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3082",
       "fake": true,
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_groups:open-audit",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - SYSTEM INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "HARDWARE MANUFACTURERS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_sys_manufacturer",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "HARDWARE MODELS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_sys_model",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 10 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "AGENTS BY NBR OF PROCESSORS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_sys_processor_count",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "PROCESSORS INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 18 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "AGENTS BY MEMORY",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_memory_item_size",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Memory\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "MEMORY INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 26 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Memory\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "AGENTS BY BIOS",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_bios_item_manufacturer",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit BIOS\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "BIOS INFO",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 34 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit BIOS\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM DRIVES",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Disk\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DISKS PARTITIONS",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Partition\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - OS INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "AGENTS BY OS FAMILY",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_sys_os_group",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "AGENTS BY OS FAMILY",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 5, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_sys_os_group",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "BOOT TIME",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data_os_boot_time",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:*inventory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OS INVENTORY",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit System\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - IPv4 INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "NIC AND IPv4",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Network\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "IPv4 ROUTE TABLE",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Route\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - INSTALLED SOFWARE AND HOTFIXES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "INSTALLED SOFTWARE - TOTAL",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "data_system_software_item_name", "id": "1", "type": "cardinality" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Software\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "INSTALLED SOFTWARE BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 4, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Software\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SOFTWARE INVENTORY",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Software\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS HOTFIXES",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Software\" AND data_system_software_item_type:update",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - SYSTEM SERVICES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL SYSTEM SERVICES",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "data_system_service_item_name", "id": "1", "type": "cardinality" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Service\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM SERVICES BY STATE",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_service_item_state",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Service\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM SERVICES BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 14 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Service\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SYSTEM SERVICES INVENTORY",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Service\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - ACTIVE DIRECTORY INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "WINDOWS DOMAINS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "data_system_windows_item_domain_short",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Windows\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "MACHINES BY DOMAIN",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_system_windows_item_domain_short",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Windows\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "MACHINES BY AD OU",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "data_system_windows_item_active_directory_ou",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Windows\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS AD",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_description:\"Open-Audit Windows\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS IMVENTORY - AD GROUP POLICIES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "AD GROUP POLICIES",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Policy\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - SCHEDULED TASKS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "SCHEDULED TASKS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit Task\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "AGENTS INVENTORY - LOCAL USER ACCOUNTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOCAL ACCOUNTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "agent_name:$agent_name AND rule_groups:open-audit AND rule_description:\"Open-Audit User\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}