{
 "title": "EDR - COMPLIANCE",
 "tags": [ "EDR" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Controlled Unclassified Information (CUI)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CUI - EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:cui_value",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CUI - SECURITY CONTROLS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "cui_value",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:74",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:cui_value",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CUI - EVENTS BY TYPE",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3082",
       "fake": true,
       "field": "rule_description",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "rule_level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:cui_value",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CUI - EVENTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:cui_value",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CUI - EVENTS BY AGENT (HISTOGRAM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:cui_value",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CUI - EVENTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule_description",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "cui_value",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND _exists_:cui_value",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NIST 800-53",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "NIST 800-53 - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_nist_800_53",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NIST 800-53 - SECURITY CONTROLS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_nist_800_53",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_nist_800_53",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NIST 800-53 - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_nist_800_53",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NIST 800-53 - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 33 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_nist_800_53",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NIST 800-53 - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_nist_800_53",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "NIST 800-53 - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "rule_description",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "rule_nist_800_53",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_nist_800_53",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "GDPR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "GDPR - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_gdpr",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GDPR - SECURITY CONTROLS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_gdpr",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_gdpr",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GDPR - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_gdpr",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GDPR - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 33 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_gdpr",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GDPR - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_gdpr",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GDPR - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "rule_description",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "rule_gdpr",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "agent_name:$agent_name AND _exists_:rule_gdpr",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}