{
 "title": "EDR - CROWDSTRIKE EVENTS AND ALERTS",
 "tags": [ "EDR" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "crowdstrike_agent",
    "label": "CROWDSTRIKE AGENT",
    "query": "{ \"find\": \"terms\", \"field\": \"dhost\", \"query\": \"\", \"size\": 1024}"
   },
   {
    "name": "crowdstrike_severity",
    "label": "CrowdStrike Severity",
    "query": "{ \"find\": \"terms\", \"field\": \"severity\", \"query\": \"\", \"size\": 1024}"
   }
  ]
 },
 "panels": [
  { "title": "CROWDSTRIKE - SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CROWDSTRIKE EDR - EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE - AGENTS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "dhost",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE EDR - EVENTS/TYPE",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "event_class_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE EDR - SEVERITY LEVELS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "severity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:74",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE EDR - EVENT GROUPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE - EVENTS BY AGENT (HISTOGRAM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dhost",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE - EVENTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CROWDSTRIKE - DETECTIONS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "DETECTION EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "name:DetectionSummaryEvent",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DETECTION EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "dhost",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "name:DetectionSummaryEvent",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "DETECTION EVENTS BY DESCRIPTION",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "msg",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "name:DetectionSummaryEvent",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CROWDSTRIKE - DETECTION EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "name:DetectionSummaryEvent",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "CROWDSTRIKE - USER ACTIVITY (CROWDSTRIKE PORTAL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "USER ACTIVITY EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_class_id:UserActivityAuditEvent",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "USER ACTIVITY - EVENTS BY USER ID",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 44 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "duser",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_class_id:UserActivityAuditEvent",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "USER ACTIVITY BY SRC IP",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "destinationTranslatedAddress",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "destinationTranslatedAddress_country_code",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "event_class_id:UserActivityAuditEvent",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CROWDSTRIKE - USER ACTIVITY EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "event_class_id:UserActivityAuditEvent",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}