"""Add display event source columns

Revision ID: 0912fd37e41c
Revises: 260371af0a48
Create Date: 2026-05-09 12:11:03.609820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0912fd37e41c'
down_revision: Union[str, None] = '260371af0a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sources', sa.Column('displayed_columns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_sources', 'displayed_columns')
    # ### end Alembic commands ###
