"""Add incident tables

Revision ID: 1501739c6898
Revises: fed7739bd07c
Create Date: 2024-07-15 09:07:17.324615

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1501739c6898"
down_revision: Union[str, None] = "fed7739bd07c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_management_alert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_name", mysql.TEXT(length=1000000), nullable=False),
        sa.Column("alert_description", mysql.TEXT(length=1000000), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("alert_creation_time", sa.DateTime(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("time_closed", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_alertcontext",
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_assetfieldname",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_case",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_name", sa.String(length=10000), nullable=False),
        sa.Column("case_description", mysql.TEXT(length=1000000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_fieldname",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_linked", sa.Integer(), nullable=True),
        sa.Column("asset_name", sa.String(length=255), nullable=False),
        sa.Column("alert_context_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(length=50), nullable=True),
        sa.Column("velociraptor_id", sa.String(length=150), nullable=True),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("index_name", sa.String(length=255), nullable=False),
        sa.Column("index_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_context_id"],
            ["incident_management_alertcontext.id"],
        ),
        sa.ForeignKeyConstraint(
            ["alert_linked"],
            ["incident_management_alert.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_casealertlink",
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["incident_management_alert.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["incident_management_case.id"],
        ),
        sa.PrimaryKeyConstraint("case_id", "alert_id"),
    )
    op.create_table(
        "incident_management_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("comment", mysql.TEXT(length=1000000), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["incident_management_alert.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_management_comment")
    op.drop_table("incident_management_casealertlink")
    op.drop_table("incident_management_asset")
    op.drop_table("incident_management_fieldname")
    op.drop_table("incident_management_case")
    op.drop_table("incident_management_assetfieldname")
    op.drop_table("incident_management_alertcontext")
    op.drop_table("incident_management_alert")
    # ### end Alembic commands ###
