"""Modify network connectors meta table

Revision ID: 16855d538921
Revises: 74a095d63af4
Create Date: 2024-04-28 10:47:04.006263

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16855d538921"
down_revision: Union[str, None] = "74a095d63af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_network_connectors_meta", sa.Column("graylog_pipeline_id", sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_network_connectors_meta", "graylog_pipeline_id")
    # ### end Alembic commands ###
