"""Add notification tablesv2

Revision ID: 260371af0a48
Revises: 458e2a7b6b11
Create Date: 2026-04-29 11:17:25.975308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '260371af0a48'
down_revision: Union[str, None] = '458e2a7b6b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_shuffle_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('shuffle_org_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_shuffle_integration_created_at'), 'customer_shuffle_integration', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_shuffle_integration_customer_code'), 'customer_shuffle_integration', ['customer_code'], unique=False)
    op.add_column('customer_notification_route', sa.Column('shuffle_integration_id', sa.Integer(), nullable=True))
    op.add_column('customer_notification_route', sa.Column('shuffle_app_id', sa.String(length=64), nullable=True))
    op.add_column('customer_notification_route', sa.Column('shuffle_app_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_customer_notification_route_shuffle_integration_id'), 'customer_notification_route', ['shuffle_integration_id'], unique=False)
    op.create_foreign_key(None, 'customer_notification_route', 'customer_shuffle_integration', ['shuffle_integration_id'], ['id'])
    op.add_column('notification_dispatch_log', sa.Column('shuffle_execution_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_dispatch_log', 'shuffle_execution_id')
    op.drop_constraint(None, 'customer_notification_route', type_='foreignkey')
    op.drop_index(op.f('ix_customer_notification_route_shuffle_integration_id'), table_name='customer_notification_route')
    op.drop_column('customer_notification_route', 'shuffle_app_name')
    op.drop_column('customer_notification_route', 'shuffle_app_id')
    op.drop_column('customer_notification_route', 'shuffle_integration_id')
    op.drop_index(op.f('ix_customer_shuffle_integration_customer_code'), table_name='customer_shuffle_integration')
    op.drop_index(op.f('ix_customer_shuffle_integration_created_at'), table_name='customer_shuffle_integration')
    op.drop_table('customer_shuffle_integration')
    # ### end Alembic commands ###
