"""Added AlertCreationSettings Table

Revision ID: 282b28f97b74
Revises: 2eed18f0c006
Create Date: 2024-04-21 16:49:59.480370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '282b28f97b74'
down_revision: Union[str, None] = '2eed18f0c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_alert_creation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=False),
    sa.Column('excluded_wazuh_rules', sa.String(length=1024), nullable=True),
    sa.Column('excluded_suricata_rules', sa.String(length=1024), nullable=True),
    sa.Column('timefield', sa.String(length=1024), nullable=True),
    sa.Column('office365_organization_id', sa.String(length=1024), nullable=True),
    sa.Column('iris_customer_id', sa.Integer(), nullable=True),
    sa.Column('iris_customer_name', sa.String(length=1024), nullable=True),
    sa.Column('iris_index', sa.String(length=1024), nullable=True),
    sa.Column('grafana_url', sa.String(length=1024), nullable=True),
    sa.Column('misp_url', sa.String(length=1024), nullable=True),
    sa.Column('opencti_url', sa.String(length=1024), nullable=True),
    sa.Column('custom_message', sa.String(length=1024), nullable=True),
    sa.Column('shuffle_endpoint', sa.String(length=1024), nullable=True),
    sa.Column('nvd_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_alert_creation_event_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_creation_settings_id', sa.Integer(), nullable=True),
    sa.Column('order_label', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['alert_creation_settings_id'], ['custom_alert_creation_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_alert_creation_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_order_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=1024), nullable=False),
    sa.Column('field_value', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['event_order_id'], ['custom_alert_creation_event_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_alert_creation_event_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_order_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=1024), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['event_order_id'], ['custom_alert_creation_event_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('connectorhistory', 'change_description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('smtp', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('smtp', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('connectorhistory', 'change_description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_table('custom_alert_creation_event_config')
    op.drop_table('custom_alert_creation_condition')
    op.drop_table('custom_alert_creation_event_order')
    op.drop_table('custom_alert_creation_settings')
    # ### end Alembic commands ###
