"""Add sca reports table

Revision ID: 2b39bb1f528f
Revises: d21f0b3329b4
Create Date: 2026-01-24 13:18:30.452434

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b39bb1f528f"
down_revision: Union[str, None] = "d21f0b3329b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sca_reports",
        sa.Column("filters_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_name", sa.String(length=255), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("bucket_name", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=128), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("generated_by", sa.Integer(), nullable=False),
        sa.Column("total_policies", sa.Integer(), nullable=False),
        sa.Column("total_checks", sa.Integer(), nullable=False),
        sa.Column("passed_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("invalid_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sca_reports_customer_code"), "sca_reports", ["customer_code"], unique=False)
    op.create_index(op.f("ix_sca_reports_generated_at"), "sca_reports", ["generated_at"], unique=False)
    op.create_index(op.f("ix_sca_reports_status"), "sca_reports", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sca_reports_status"), table_name="sca_reports")
    op.drop_index(op.f("ix_sca_reports_generated_at"), table_name="sca_reports")
    op.drop_index(op.f("ix_sca_reports_customer_code"), table_name="sca_reports")
    op.drop_table("sca_reports")
    # ### end Alembic commands ###
