"""Added Agents Table

Revision ID: 2eed18f0c006
Revises: be2c26d59d73
Create Date: 2024-04-21 16:44:21.209742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2eed18f0c006'
down_revision: Union[str, None] = 'be2c26d59d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('parent_customer_code', sa.String(length=11), nullable=True),
    sa.Column('customer_name', sa.String(length=50), nullable=False),
    sa.Column('contact_last_name', sa.String(length=50), nullable=True),
    sa.Column('contact_first_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=1024), nullable=True),
    sa.Column('address_line2', sa.String(length=1024), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=15), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('logo_file', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=False)
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=1024), nullable=False),
    sa.Column('customer_name', sa.String(length=1024), nullable=False),
    sa.Column('customer_email', sa.String(length=1024), nullable=False),
    sa.Column('company_name', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=256), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=5024), nullable=True),
    sa.Column('additional_info', sa.String(length=5024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=256), nullable=False),
    sa.Column('ip_address', sa.String(length=256), nullable=False),
    sa.Column('os', sa.String(length=256), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('critical_asset', sa.Boolean(), nullable=False),
    sa.Column('wazuh_last_seen', sa.DateTime(), nullable=False),
    sa.Column('velociraptor_id', sa.String(length=256), nullable=False),
    sa.Column('velociraptor_last_seen', sa.DateTime(), nullable=False),
    sa.Column('wazuh_agent_version', sa.String(length=256), nullable=False),
    sa.Column('wazuh_agent_status', sa.String(length=256), nullable=False),
    sa.Column('velociraptor_agent_version', sa.String(length=256), nullable=False),
    sa.Column('customer_code', sa.String(length=256), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_table('customersmeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_meta_graylog_index', sa.String(length=1024), nullable=False),
    sa.Column('customer_meta_graylog_stream', sa.String(length=1024), nullable=False),
    sa.Column('customer_meta_grafana_org_id', sa.String(length=1024), nullable=False),
    sa.Column('customer_meta_wazuh_group', sa.String(length=1024), nullable=False),
    sa.Column('customer_meta_index_retention', sa.String(length=1024), nullable=True),
    sa.Column('customer_meta_wazuh_registration_port', sa.String(length=1024), nullable=True),
    sa.Column('customer_meta_wazuh_log_ingestion_port', sa.String(length=1024), nullable=True),
    sa.Column('customer_meta_wazuh_api_port', sa.String(length=1024), nullable=True),
    sa.Column('customer_meta_wazuh_auth_password', sa.String(length=1024), nullable=True),
    sa.Column('customer_meta_iris_customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_meta_office365_organization_id', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('connectorhistory', 'change_description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('smtp', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('smtp', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('connectorhistory', 'change_description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_table('customersmeta')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('log_entries')
    op.drop_table('license')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
