"""Add to snapshot and restore

Revision ID: 2ef4b8b77790
Revises: 980bb08dd1cd
Create Date: 2026-04-26 17:02:24.164444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ef4b8b77790'
down_revision: Union[str, None] = '980bb08dd1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_snapshot_schedules', sa.Column('scheduled_hour', sa.Integer(), nullable=True))
    op.add_column('index_snapshot_schedules', sa.Column('scheduled_minute', sa.Integer(), nullable=True))
    op.add_column('index_snapshot_schedules', sa.Column('interval_days', sa.Integer(), nullable=False))
    op.add_column('index_snapshot_schedules', sa.Column('timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_snapshot_schedules', 'timezone')
    op.drop_column('index_snapshot_schedules', 'interval_days')
    op.drop_column('index_snapshot_schedules', 'scheduled_minute')
    op.drop_column('index_snapshot_schedules', 'scheduled_hour')
    # ### end Alembic commands ###
