"""Update integration details to no max length

Revision ID: 30955781e02d
Revises: 95b24e727707
Create Date: 2024-04-22 09:57:25.238006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30955781e02d'
down_revision: Union[str, None] = '95b24e727707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_integrations', 'integration_details',
               existing_type=sa.String(length=10000024),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('connectorhistory', 'change_description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('scheduled_job_metadata', 'job_id',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('scheduled_job_metadata', 'extra_data',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('smtp', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('smtp', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('scheduled_job_metadata', 'extra_data',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('scheduled_job_metadata', 'job_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('connectorhistory', 'change_description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('available_integrations', 'integration_details',
               existing_type=sa.Text(),
               type_=sa.String(length=10000024),
               existing_nullable=False)
    # ### end Alembic commands ###
