"""Add ioc table for alerts

Revision ID: 33e4754d845b
Revises: a1e4beb87498
Create Date: 2024-10-30 15:16:50.509086

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33e4754d845b"
down_revision: Union[str, None] = "a1e4beb87498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_management_ioc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=250), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=10000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_management_alert_to_ioc",
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("ioc_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["incident_management_alert.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ioc_id"],
            ["incident_management_ioc.id"],
        ),
        sa.PrimaryKeyConstraint("alert_id", "ioc_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_management_alert_to_ioc")
    op.drop_table("incident_management_ioc")
    # ### end Alembic commands ###
