"""New agents table schema

Revision ID: 39c3aaec0084
Revises: ec63589cc24d
Create Date: 2024-05-17 17:17:39.140779

"""
from typing import Sequence
from typing import Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39c3aaec0084"
down_revision: Union[str, None] = "ec63589cc24d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("agents", "velociraptor_id", existing_type=mysql.VARCHAR(length=256), nullable=True)
    op.alter_column("agents", "velociraptor_last_seen", existing_type=mysql.DATETIME(), nullable=True)
    op.alter_column("agents", "velociraptor_agent_version", existing_type=mysql.VARCHAR(length=256), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("agents", "velociraptor_agent_version", existing_type=mysql.VARCHAR(length=256), nullable=False)
    op.alter_column("agents", "velociraptor_last_seen", existing_type=mysql.DATETIME(), nullable=False)
    op.alter_column("agents", "velociraptor_id", existing_type=mysql.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###
