"""Add notification tables

Revision ID: 458e2a7b6b11
Revises: 03508fb56a48
Create Date: 2026-04-29 10:40:19.212448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '458e2a7b6b11'
down_revision: Union[str, None] = '03508fb56a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_notification_route',
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('format_template', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notification_route_created_at'), 'customer_notification_route', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_notification_route_customer_code'), 'customer_notification_route', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customer_notification_route_trigger'), 'customer_notification_route', ['trigger'], unique=False)
    op.create_table('notification_dispatch_log',
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_preview', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['customer_notification_route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code', 'alert_id', 'route_id', 'trigger', name='uq_notif_dispatch_idem')
    )
    op.create_index(op.f('ix_notification_dispatch_log_alert_id'), 'notification_dispatch_log', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notification_dispatch_log_customer_code'), 'notification_dispatch_log', ['customer_code'], unique=False)
    op.create_index(op.f('ix_notification_dispatch_log_dispatched_at'), 'notification_dispatch_log', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_notification_dispatch_log_route_id'), 'notification_dispatch_log', ['route_id'], unique=False)
    op.create_index(op.f('ix_notification_dispatch_log_status'), 'notification_dispatch_log', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_dispatch_log_status'), table_name='notification_dispatch_log')
    op.drop_index(op.f('ix_notification_dispatch_log_route_id'), table_name='notification_dispatch_log')
    op.drop_index(op.f('ix_notification_dispatch_log_dispatched_at'), table_name='notification_dispatch_log')
    op.drop_index(op.f('ix_notification_dispatch_log_customer_code'), table_name='notification_dispatch_log')
    op.drop_index(op.f('ix_notification_dispatch_log_alert_id'), table_name='notification_dispatch_log')
    op.drop_table('notification_dispatch_log')
    op.drop_index(op.f('ix_customer_notification_route_trigger'), table_name='customer_notification_route')
    op.drop_index(op.f('ix_customer_notification_route_customer_code'), table_name='customer_notification_route')
    op.drop_index(op.f('ix_customer_notification_route_created_at'), table_name='customer_notification_route')
    op.drop_table('customer_notification_route')
    # ### end Alembic commands ###
