"""Add escalated column to alerts and cases

Revision ID: 47c5adfa3c7e
Revises: 5599c90717d4
Create Date: 2025-09-19 13:55:35.348208

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47c5adfa3c7e"
down_revision: Union[str, None] = "5599c90717d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_management_alert", sa.Column("escalated", sa.Boolean(), nullable=False))
    op.add_column("incident_management_case", sa.Column("escalated", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_management_case", "escalated")
    op.drop_column("incident_management_alert", "escalated")
    # ### end Alembic commands ###
