"""Add to snapshot and restore day of week

Revision ID: 51e33a247851
Revises: 2ef4b8b77790
Create Date: 2026-04-26 17:27:17.439132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51e33a247851'
down_revision: Union[str, None] = '2ef4b8b77790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_snapshot_schedules', sa.Column('day_of_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_snapshot_schedules', 'day_of_week')
    # ### end Alembic commands ###
