"""Remove customer code column from agent datastore

Revision ID: 53e04a4c4ff3
Revises: 5c588e7cb55c
Create Date: 2025-11-27 10:04:02.283557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53e04a4c4ff3'
down_revision: Union[str, None] = '5c588e7cb55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint FIRST
    op.drop_constraint('agent_datastore_ibfk_2', 'agent_datastore', type_='foreignkey')
    # Then drop the index
    op.drop_index('ix_agent_datastore_customer_code', table_name='agent_datastore')
    # Finally drop the column
    op.drop_column('agent_datastore', 'customer_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column first
    op.add_column('agent_datastore', sa.Column('customer_code', mysql.VARCHAR(length=50), nullable=False))
    # Then create the index
    op.create_index('ix_agent_datastore_customer_code', 'agent_datastore', ['customer_code'], unique=False)
    # Finally create the foreign key
    op.create_foreign_key('agent_datastore_ibfk_2', 'agent_datastore', 'customers', ['customer_code'], ['customer_code'])
    # ### end Alembic commands ###
