"""Add agent datastore

Revision ID: 5c588e7cb55c
Revises: 1dd1c055ee06
Create Date: 2025-11-27 09:39:47.952715

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c588e7cb55c"
down_revision: Union[str, None] = "1dd1c055ee06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_datastore",
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(length=256), nullable=False),
        sa.Column("velociraptor_id", sa.String(length=256), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("artifact_name", sa.String(length=255), nullable=False),
        sa.Column("flow_id", sa.String(length=255), nullable=False),
        sa.Column("collection_time", sa.DateTime(), nullable=False),
        sa.Column("bucket_name", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=128), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.agent_id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_datastore_agent_id"), "agent_datastore", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_datastore_artifact_name"), "agent_datastore", ["artifact_name"], unique=False)
    op.create_index(op.f("ix_agent_datastore_collection_time"), "agent_datastore", ["collection_time"], unique=False)
    op.create_index(op.f("ix_agent_datastore_customer_code"), "agent_datastore", ["customer_code"], unique=False)
    op.create_index(op.f("ix_agent_datastore_flow_id"), "agent_datastore", ["flow_id"], unique=False)
    op.create_index(op.f("ix_agent_datastore_status"), "agent_datastore", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_datastore_status"), table_name="agent_datastore")
    op.drop_index(op.f("ix_agent_datastore_flow_id"), table_name="agent_datastore")
    op.drop_index(op.f("ix_agent_datastore_customer_code"), table_name="agent_datastore")
    op.drop_index(op.f("ix_agent_datastore_collection_time"), table_name="agent_datastore")
    op.drop_index(op.f("ix_agent_datastore_artifact_name"), table_name="agent_datastore")
    op.drop_index(op.f("ix_agent_datastore_agent_id"), table_name="agent_datastore")
    op.drop_table("agent_datastore")
    # ### end Alembic commands ###
