"""add_user_last_login_at

Revision ID: 649e1a544188
Revises: 1732924fe14f
Create Date: 2026-06-25 13:53:33.000025

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "649e1a544188"
down_revision: Union[str, None] = "1732924fe14f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login_at")
    # ### end Alembic commands ###
