"""Add license cache table

Revision ID: 6796a7d001ad
Revises: 8e3b57c8bbb2
Create Date: 2025-09-02 09:58:22.242700

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6796a7d001ad"
down_revision: Union[str, None] = "8e3b57c8bbb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("license_key", sa.String(length=1024), nullable=False),
        sa.Column("feature_name", sa.String(length=256), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("license_data", sa.String(length=5000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_license_cache_cached_at"), "license_cache", ["cached_at"], unique=False)
    op.create_index(op.f("ix_license_cache_expires_at"), "license_cache", ["expires_at"], unique=False)
    op.create_index(op.f("ix_license_cache_feature_name"), "license_cache", ["feature_name"], unique=False)

    # Create partial index on license_key (first 255 characters to avoid MySQL key length limit)
    op.execute("CREATE INDEX ix_license_cache_license_key ON license_cache (license_key(255))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_license_cache_license_key", table_name="license_cache")
    op.drop_index(op.f("ix_license_cache_feature_name"), table_name="license_cache")
    op.drop_index(op.f("ix_license_cache_expires_at"), table_name="license_cache")
    op.drop_index(op.f("ix_license_cache_cached_at"), table_name="license_cache")
    op.drop_table("license_cache")
    # ### end Alembic commands ###
