"""Add portainer stack id column to customer meta

Revision ID: 6ac2c9c193a8
Revises: b453170bbefc
Create Date: 2025-02-20 15:13:41.397420

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ac2c9c193a8"
down_revision: Union[str, None] = "b453170bbefc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customersmeta", sa.Column("customer_meta_portainer_stack_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customersmeta", "customer_meta_portainer_stack_id")
    # ### end Alembic commands ###
