"""Add case template tables

Revision ID: 6ba5c2887ec5
Revises: 51e33a247851
Create Date: 2026-04-26 19:01:10.218459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ba5c2887ec5'
down_revision: Union[str, None] = '51e33a247851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_management_case_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_case_event',
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['incident_management_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_management_case_event_case_id'), 'incident_management_case_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_incident_management_case_event_event_type'), 'incident_management_case_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_incident_management_case_event_timestamp'), 'incident_management_case_event', ['timestamp'], unique=False)
    op.create_table('incident_management_case_template_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('guidelines', sa.String(length=255), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['incident_management_case_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_case_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('template_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('guidelines', sa.String(length=255), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_comment', sa.String(length=255), nullable=True),
    sa.Column('completed_by', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['incident_management_case.id'], ),
    sa.ForeignKeyConstraint(['template_task_id'], ['incident_management_case_template_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_management_case_task')
    op.drop_table('incident_management_case_template_task')
    op.drop_index(op.f('ix_incident_management_case_event_timestamp'), table_name='incident_management_case_event')
    op.drop_index(op.f('ix_incident_management_case_event_event_type'), table_name='incident_management_case_event')
    op.drop_index(op.f('ix_incident_management_case_event_case_id'), table_name='incident_management_case_event')
    op.drop_table('incident_management_case_event')
    op.drop_table('incident_management_case_template')
    # ### end Alembic commands ###
