"""Remove logo_base64 column

Revision ID: 74727b1f75e6
Revises: 53e04a4c4ff3
Create Date: 2025-11-29 09:26:08.423329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74727b1f75e6'
down_revision: Union[str, None] = '53e04a4c4ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_portal_settings', 'logo_base64')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_portal_settings', sa.Column('logo_base64', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
