"""Add Network Connectors Tables

Revision ID: 74a095d63af4
Revises: c3ad5012f4db
Create Date: 2024-04-25 13:03:22.718120

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74a095d63af4"
down_revision: Union[str, None] = "c3ad5012f4db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "available_network_connectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("network_connector_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("network_connector_details", mysql.TEXT(length=1000000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer_network_connectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("network_connector_service_id", sa.Integer(), nullable=False),
        sa.Column("network_connector_service_name", sa.String(length=255), nullable=False),
        sa.Column("deployed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer_network_connectors_meta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("network_connector_name", sa.String(length=255), nullable=False),
        sa.Column("graylog_input_id", sa.String(length=1024), nullable=True),
        sa.Column("graylog_index_id", sa.String(length=1024), nullable=False),
        sa.Column("graylog_stream_id", sa.String(length=1024), nullable=False),
        sa.Column("grafana_org_id", sa.String(length=1024), nullable=False),
        sa.Column("grafana_dashboard_folder_id", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_connectors_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "available_network_connectors_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("network_connector_id", sa.Integer(), nullable=True),
        sa.Column("network_connector_name", sa.String(length=255), nullable=False),
        sa.Column("auth_key_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["network_connector_id"],
            ["available_network_connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_connectors_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("network_connector_service_id", sa.Integer(), nullable=True),
        sa.Column("config_key", sa.String(length=255), nullable=False),
        sa.Column("config_value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["network_connector_service_id"],
            ["network_connectors_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_connectors_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("network_connectors_service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer_network_connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_connectors_service_id"],
            ["network_connectors_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_connectors_keys",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("subscription_id", sa.Integer(), nullable=True),
        sa.Column("auth_key_name", sa.String(length=255), nullable=False),
        sa.Column("auth_value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["network_connectors_subscriptions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("network_connectors_keys")
    op.drop_table("network_connectors_subscriptions")
    op.drop_table("network_connectors_configs")
    op.drop_table("available_network_connectors_keys")
    op.drop_table("network_connectors_services")
    op.drop_table("customer_network_connectors_meta")
    op.drop_table("customer_network_connectors")
    op.drop_table("available_network_connectors")
    # ### end Alembic commands ###
