"""Add customer code to vulnerabilities table

Revision ID: 7b2bbee2f3e8
Revises: dd0e62747e2c
Create Date: 2025-09-09 15:17:41.770559

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b2bbee2f3e8"
down_revision: Union[str, None] = "dd0e62747e2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_vulnerabilities", sa.Column("customer_code", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_agent_vulnerabilities_customer_code"), "agent_vulnerabilities", ["customer_code"], unique=False)
    op.create_foreign_key(None, "agent_vulnerabilities", "customers", ["customer_code"], ["customer_code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agent_vulnerabilities", type_="foreignkey")
    op.drop_index(op.f("ix_agent_vulnerabilities_customer_code"), table_name="agent_vulnerabilities")
    op.drop_column("agent_vulnerabilities", "customer_code")
    # ### end Alembic commands ###
