"""Add sigma queries table

Revision ID: 7f846a07c2b8
Revises: 7187bab836ab
Create Date: 2024-07-31 11:20:41.741602

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f846a07c2b8"
down_revision: Union[str, None] = "7187bab836ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sigma_queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_name", mysql.TEXT(length=1000000), nullable=False),
        sa.Column("rule_query", mysql.TEXT(length=1000000), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("time_interval", sa.String(length=50), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("last_execution_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sigma_queries")
    # ### end Alembic commands ###
