"""Add edr_install command columns

Revision ID: 846d8c07dd98
Revises: e4f5a6b7c8d9
Create Date: 2026-06-16 15:59:31.930531

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "846d8c07dd98"
down_revision: Union[str, None] = "e4f5a6b7c8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_provisioning_default_settings", sa.Column("repo_url", sa.String(length=1024), nullable=True))
    op.add_column("customer_provisioning_default_settings", sa.Column("repo_username", sa.String(length=255), nullable=True))
    op.add_column("customer_provisioning_default_settings", sa.Column("repo_password", sa.String(length=1024), nullable=True))
    op.add_column("customer_provisioning_default_settings", sa.Column("windows_edr_installer", sa.String(length=255), nullable=True))
    op.add_column("customer_provisioning_default_settings", sa.Column("wazuh_domain", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_provisioning_default_settings", "wazuh_domain")
    op.drop_column("customer_provisioning_default_settings", "windows_edr_installer")
    op.drop_column("customer_provisioning_default_settings", "repo_password")
    op.drop_column("customer_provisioning_default_settings", "repo_username")
    op.drop_column("customer_provisioning_default_settings", "repo_url")
    # ### end Alembic commands ###
