"""Add event sources tables

Revision ID: 85ea2970828c
Revises: fb51d610b306
Create Date: 2026-03-13 17:00:07.745510

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85ea2970828c"
down_revision: Union[str, None] = "fb51d610b306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("index_pattern", sa.String(length=1024), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("time_field", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_sources_customer_code"), "event_sources", ["customer_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_sources_customer_code"), table_name="event_sources")
    op.drop_table("event_sources")
    # ### end Alembic commands ###
