"""add case task

Revision ID: 87cd5b105199
Revises: e7f8a9b0c1d2
Create Date: 2026-08-01 13:40:38.206125

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87cd5b105199"
down_revision: Union[str, None] = "e7f8a9b0c1d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_management_case_task", sa.Column("assigned_to", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_incident_management_case_task_assigned_to"), "incident_management_case_task", ["assigned_to"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incident_management_case_task_assigned_to"), table_name="incident_management_case_task")
    op.drop_column("incident_management_case_task", "assigned_to")
    # ### end Alembic commands ###
