"""Add incident thresholds tables

Revision ID: 895843b96397
Revises: 8e6302c4877d
Create Date: 2026-03-19 11:48:17.809975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '895843b96397'
down_revision: Union[str, None] = '8e6302c4877d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_management_threshold_alert_metadata',
    sa.Column('group_by_fields', sa.JSON(), nullable=True),
    sa.Column('source_streams', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_definition_id', sa.String(length=255), nullable=False),
    sa.Column('replay_query', sa.String(length=255), nullable=False),
    sa.Column('timerange_start', sa.DateTime(), nullable=False),
    sa.Column('timerange_end', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('resolved_index_name', sa.String(length=255), nullable=False),
    sa.Column('resolved_index_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['incident_management_alert.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_management_threshold_alert_metadata')
    # ### end Alembic commands ###
