"""Add index snapshots table

Revision ID: 8c419faae3e5
Revises: 2b39bb1f528f
Create Date: 2026-01-28 13:22:53.153175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c419faae3e5'
down_revision: Union[str, None] = '2b39bb1f528f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_snapshot_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('index_pattern', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('snapshot_prefix', sa.String(length=255), nullable=False),
    sa.Column('include_global_state', sa.Boolean(), nullable=False),
    sa.Column('skip_write_indices', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('last_execution_time', sa.DateTime(), nullable=True),
    sa.Column('last_snapshot_name', sa.String(length=255), nullable=True),
    sa.Column('last_execution_status', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_snapshot_schedules')
    # ### end Alembic commands ###
