"""Add grafana_datasource_uid to customer integrations meta table

Revision ID: 8e3b57c8bbb2
Revises: 53ca91e8a196
Create Date: 2025-06-20 16:18:50.121209

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e3b57c8bbb2"
down_revision: Union[str, None] = "53ca91e8a196"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_integrations_meta", sa.Column("grafana_datasource_uid", sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_integrations_meta", "grafana_datasource_uid")
    # ### end Alembic commands ###
