"""Add enabled dashboards tables

Revision ID: 8e6302c4877d
Revises: 85ea2970828c
Create Date: 2026-03-17 14:44:04.797718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e6302c4877d'
down_revision: Union[str, None] = '85ea2970828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enabled_dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('event_source_id', sa.Integer(), nullable=False),
    sa.Column('library_card', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.ForeignKeyConstraint(['event_source_id'], ['event_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code', 'event_source_id', 'library_card', 'template_id', name='uq_enabled_dashboard')
    )
    op.create_index(op.f('ix_enabled_dashboards_customer_code'), 'enabled_dashboards', ['customer_code'], unique=False)
    op.create_index(op.f('ix_enabled_dashboards_event_source_id'), 'enabled_dashboards', ['event_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enabled_dashboards_event_source_id'), table_name='enabled_dashboards')
    op.drop_index(op.f('ix_enabled_dashboards_customer_code'), table_name='enabled_dashboards')
    op.drop_table('enabled_dashboards')
    # ### end Alembic commands ###
