"""Added Monitoring Alerts Tables

Revision ID: 93efaef3c7df
Revises: aa96830e4555
Create Date: 2024-04-21 17:08:49.209615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93efaef3c7df'
down_revision: Union[str, None] = 'aa96830e4555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('monitoring_alerts',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('alert_id', sa.String(length=1024), nullable=False),
    # sa.Column('alert_index', sa.String(length=1024), nullable=False),
    # sa.Column('customer_code', sa.String(length=50), nullable=False),
    # sa.Column('alert_source', sa.String(length=1024), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    #op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    #op.drop_table('apscheduler_jobs')
    op.alter_column('connectorhistory', 'change_description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('scheduled_job_metadata', 'job_id',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('scheduled_job_metadata', 'extra_data',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('smtp', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('smtp', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('scheduled_job_metadata', 'extra_data',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('scheduled_job_metadata', 'job_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('connectorhistory', 'change_description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    # op.create_table('apscheduler_jobs',
    # sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    # sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    # sa.Column('job_state', sa.BLOB(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    #op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    #op.drop_table('monitoring_alerts')
    # ### end Alembic commands ###
