"""Add drawer_id and expired_at to ai_analyst_palace_lesson

Revision ID: 980bb08dd1cd
Revises: e01d1d2600eb
Create Date: 2026-04-22 14:07:21.240770

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "980bb08dd1cd"
down_revision: Union[str, None] = "e01d1d2600eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_analyst_palace_lesson", sa.Column("drawer_id", sa.String(length=64), nullable=True))
    op.add_column("ai_analyst_palace_lesson", sa.Column("expired_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_ai_analyst_palace_lesson_drawer_id"), "ai_analyst_palace_lesson", ["drawer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_analyst_palace_lesson_drawer_id"), table_name="ai_analyst_palace_lesson")
    op.drop_column("ai_analyst_palace_lesson", "expired_at")
    op.drop_column("ai_analyst_palace_lesson", "drawer_id")
    # ### end Alembic commands ###
