"""Add alert_id column for tasks

Revision ID: 9c815bd72392
Revises: 0912fd37e41c
Create Date: 2026-05-18 12:05:21.941709

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c815bd72392"
down_revision: Union[str, None] = "0912fd37e41c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_management_case_task", sa.Column("alert_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_incident_management_case_task_alert_id"), "incident_management_case_task", ["alert_id"], unique=False)
    op.create_foreign_key(None, "incident_management_case_task", "incident_management_alert", ["alert_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incident_management_case_task", type_="foreignkey")
    op.drop_index(op.f("ix_incident_management_case_task_alert_id"), table_name="incident_management_case_task")
    op.drop_column("incident_management_case_task", "alert_id")
    # ### end Alembic commands ###
