"""Added CustomerIntegrations Tables

Revision ID: a15814e9a45e
Revises: 282b28f97b74
Create Date: 2024-04-21 16:54:10.490320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a15814e9a45e'
down_revision: Union[str, None] = '282b28f97b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('integration_details', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('integration_service_id', sa.Integer(), nullable=False),
    sa.Column('integration_service_name', sa.String(length=255), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_integrations_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('integration_name', sa.String(length=255), nullable=False),
    sa.Column('graylog_input_id', sa.String(length=1024), nullable=True),
    sa.Column('graylog_index_id', sa.String(length=1024), nullable=False),
    sa.Column('graylog_stream_id', sa.String(length=1024), nullable=False),
    sa.Column('grafana_org_id', sa.String(length=1024), nullable=False),
    sa.Column('grafana_dashboard_folder_id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('available_integrations_auth_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('integration_name', sa.String(length=255), nullable=False),
    sa.Column('auth_key_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['available_integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_service_id', sa.Integer(), nullable=True),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['integration_service_id'], ['integration_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('integration_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_integrations.id'], ),
    sa.ForeignKeyConstraint(['integration_service_id'], ['integration_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_auth_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('auth_key_name', sa.String(length=255), nullable=False),
    sa.Column('auth_value', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['integration_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('connectorhistory', 'change_description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('smtp', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('smtp', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('customersmeta', 'customer_meta_wazuh_api_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_log_ingestion_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_wazuh_registration_port',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('customersmeta', 'customer_meta_index_retention',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('connectorhistory', 'change_description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_table('integration_auth_keys')
    op.drop_table('integration_subscriptions')
    op.drop_table('integration_configs')
    op.drop_table('available_integrations_auth_keys')
    op.drop_table('integration_services')
    op.drop_table('customer_integrations_meta')
    op.drop_table('customer_integrations')
    op.drop_table('available_integrations')
    # ### end Alembic commands ###
