"""Add match_field and match_value column for tasks

Revision ID: a1960bcb4526
Revises: 9c815bd72392
Create Date: 2026-05-18 14:51:11.405635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1960bcb4526'
down_revision: Union[str, None] = '9c815bd72392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_management_case_template', sa.Column('match_field', sa.String(length=255), nullable=True))
    op.add_column('incident_management_case_template', sa.Column('match_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_management_case_template', 'match_value')
    op.drop_column('incident_management_case_template', 'match_field')
    # ### end Alembic commands ###
