"""Add Incident Management Tables

Revision ID: a54315291e03
Revises: fed7739bd07c
Create Date: 2024-07-14 11:14:15.819375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'a54315291e03'
down_revision: Union[str, None] = 'fed7739bd07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_management_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_creation_time', sa.DateTime(), nullable=False),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_closed', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_alertcontext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_casealertlink',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('case_id', 'alert_id')
    )
    op.create_table('incident_management_asset',
    sa.Column('alert_context', mysql.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_linked', sa.Integer(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('velociraptor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['alert_linked'], ['incident_management_alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_assetfieldname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_context_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_context_id'], ['incident_management_alertcontext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['incident_management_alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_management_fieldname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_context_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_context_id'], ['incident_management_alertcontext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_management_fieldname')
    op.drop_table('incident_management_comment')
    op.drop_table('incident_management_assetfieldname')
    op.drop_table('incident_management_asset')
    op.drop_table('incident_management_casealertlink')
    op.drop_table('incident_management_case')
    op.drop_table('incident_management_alertcontext')
    op.drop_table('incident_management_alert')
    # ### end Alembic commands ###
