"""Add brand_color column to customer_portal_settings

Revision ID: b3d4e5f6a7b8
Revises: f0a1b2c3d4e5
Create Date: 2026-07-21 00:00:00.000000

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3d4e5f6a7b8"
down_revision: Union[str, None] = "f0a1b2c3d4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_portal_settings", sa.Column("brand_color", sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_portal_settings", "brand_color")
    # ### end Alembic commands ###
