"""Add customer code column to cases table

Revision ID: ba64d98dbdc5
Revises: 068f32ae5984
Create Date: 2024-09-18 08:25:27.546888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba64d98dbdc5'
down_revision: Union[str, None] = '068f32ae5984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_management_case', sa.Column('customer_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_management_case', 'customer_code')
    # ### end Alembic commands ###
