"""Initial database migration

Revision ID: bdf40d064ed1
Revises:
Create Date: 2024-04-22 19:48:15.129902

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlalchemy.dialects.mysql as mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdf40d064ed1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "available_integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("integration_details", mysql.TEXT(length=1000000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connector_name", sa.String(length=256), nullable=False),
        sa.Column("connector_type", sa.String(length=256), nullable=False),
        sa.Column("connector_url", sa.String(length=750), nullable=False),
        sa.Column("connector_last_updated", sa.DateTime(), nullable=False),
        sa.Column("connector_username", sa.String(length=256), nullable=True),
        sa.Column("connector_password", sa.String(length=256), nullable=True),
        sa.Column("connector_api_key", sa.String(length=750), nullable=True),
        sa.Column("connector_description", sa.String(length=1000), nullable=True),
        sa.Column("connector_supports", sa.String(length=1000), nullable=True),
        sa.Column("connector_configured", sa.Boolean(), nullable=False),
        sa.Column("connector_verified", sa.Boolean(), nullable=False),
        sa.Column("connector_accepts_host_only", sa.Boolean(), nullable=False),
        sa.Column("connector_accepts_api_key", sa.Boolean(), nullable=False),
        sa.Column("connector_accepts_username_password", sa.Boolean(), nullable=False),
        sa.Column("connector_accepts_file", sa.Boolean(), nullable=False),
        sa.Column("connector_accepts_extra_data", sa.Boolean(), nullable=False),
        sa.Column("connector_extra_data", sa.String(length=1000), nullable=True),
        sa.Column("connector_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "custom_alert_creation_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("customer_name", sa.String(length=50), nullable=False),
        sa.Column("excluded_wazuh_rules", sa.String(length=1024), nullable=True),
        sa.Column("excluded_suricata_rules", sa.String(length=1024), nullable=True),
        sa.Column("timefield", sa.String(length=1024), nullable=True),
        sa.Column("office365_organization_id", sa.String(length=1024), nullable=True),
        sa.Column("iris_customer_id", sa.Integer(), nullable=True),
        sa.Column("iris_customer_name", sa.String(length=1024), nullable=True),
        sa.Column("iris_index", sa.String(length=1024), nullable=True),
        sa.Column("grafana_url", sa.String(length=1024), nullable=True),
        sa.Column("misp_url", sa.String(length=1024), nullable=True),
        sa.Column("opencti_url", sa.String(length=1024), nullable=True),
        sa.Column("custom_message", sa.String(length=1024), nullable=True),
        sa.Column("shuffle_endpoint", sa.String(length=1024), nullable=True),
        sa.Column("nvd_url", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer_integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("integration_service_id", sa.Integer(), nullable=False),
        sa.Column("integration_service_name", sa.String(length=255), nullable=False),
        sa.Column("deployed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer_integrations_meta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("integration_name", sa.String(length=255), nullable=False),
        sa.Column("graylog_input_id", sa.String(length=1024), nullable=True),
        sa.Column("graylog_index_id", sa.String(length=1024), nullable=False),
        sa.Column("graylog_stream_id", sa.String(length=1024), nullable=False),
        sa.Column("grafana_org_id", sa.String(length=1024), nullable=False),
        sa.Column("grafana_dashboard_folder_id", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer_provisioning_default_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_name", sa.String(length=50), nullable=False),
        sa.Column("cluster_key", sa.String(length=1000), nullable=False),
        sa.Column("master_ip", sa.String(length=50), nullable=False),
        sa.Column("grafana_url", sa.String(length=1024), nullable=False),
        sa.Column("wazuh_worker_hostname", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("parent_customer_code", sa.String(length=11), nullable=True),
        sa.Column("customer_name", sa.String(length=50), nullable=False),
        sa.Column("contact_last_name", sa.String(length=50), nullable=True),
        sa.Column("contact_first_name", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address_line1", sa.String(length=1024), nullable=True),
        sa.Column("address_line2", sa.String(length=1024), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("postal_code", sa.String(length=15), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("customer_type", sa.String(length=50), nullable=True),
        sa.Column("logo_file", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_customer_code"), "customers", ["customer_code"], unique=False)
    op.create_table(
        "integration_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "license",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("license_key", sa.String(length=1024), nullable=False),
        sa.Column("customer_name", sa.String(length=1024), nullable=False),
        sa.Column("customer_email", sa.String(length=1024), nullable=False),
        sa.Column("company_name", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("route", sa.String(length=256), nullable=True),
        sa.Column("method", sa.String(length=256), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=5024), nullable=True),
        sa.Column("additional_info", sa.String(length=5024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "monitoring_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.String(length=1024), nullable=False),
        sa.Column("alert_index", sa.String(length=1024), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("alert_source", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduled_job_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=256), nullable=False),
        sa.Column("last_success", sa.DateTime(), nullable=True),
        sa.Column("time_interval", sa.Integer(), nullable=False),
        sa.Column("extra_data", sa.String(length=256), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduled_job_metadata_job_id"), "scheduled_job_metadata", ["job_id"], unique=False)
    op.create_table(
        "schedulerjob",
        sa.Column("next_run_time", sa.Float(), nullable=True),
        sa.Column("job_state", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedulerjob_next_run_time"), "schedulerjob", ["next_run_time"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(length=256), nullable=False),
        sa.Column("ip_address", sa.String(length=256), nullable=False),
        sa.Column("os", sa.String(length=256), nullable=False),
        sa.Column("hostname", sa.String(length=256), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("critical_asset", sa.Boolean(), nullable=False),
        sa.Column("wazuh_last_seen", sa.DateTime(), nullable=False),
        sa.Column("velociraptor_id", sa.String(length=256), nullable=False),
        sa.Column("velociraptor_last_seen", sa.DateTime(), nullable=False),
        sa.Column("wazuh_agent_version", sa.String(length=256), nullable=False),
        sa.Column("wazuh_agent_status", sa.String(length=256), nullable=False),
        sa.Column("velociraptor_agent_version", sa.String(length=256), nullable=False),
        sa.Column("customer_code", sa.String(length=256), nullable=True),
        sa.Column("quarantined", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_agent_id"), "agents", ["agent_id"], unique=False)
    op.create_table(
        "available_integrations_auth_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("integration_name", sa.String(length=255), nullable=False),
        sa.Column("auth_key_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["available_integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connectorhistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connector_id", sa.Integer(), nullable=False),
        sa.Column("change_timestamp", sa.DateTime(), nullable=False),
        sa.Column("change_description", sa.String(length=10000), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "custom_alert_creation_event_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_creation_settings_id", sa.Integer(), nullable=True),
        sa.Column("order_label", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_creation_settings_id"],
            ["custom_alert_creation_settings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customersmeta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=255), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_meta_graylog_index", sa.String(length=1024), nullable=False),
        sa.Column("customer_meta_graylog_stream", sa.String(length=1024), nullable=False),
        sa.Column("customer_meta_grafana_org_id", sa.String(length=1024), nullable=False),
        sa.Column("customer_meta_wazuh_group", sa.String(length=1024), nullable=False),
        sa.Column("customer_meta_index_retention", sa.String(length=1024), nullable=True),
        sa.Column("customer_meta_wazuh_registration_port", sa.String(length=1024), nullable=True),
        sa.Column("customer_meta_wazuh_log_ingestion_port", sa.String(length=1024), nullable=True),
        sa.Column("customer_meta_wazuh_api_port", sa.String(length=1024), nullable=True),
        sa.Column("customer_meta_wazuh_auth_password", sa.String(length=1024), nullable=True),
        sa.Column("customer_meta_iris_customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_meta_office365_organization_id", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "integration_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_service_id", sa.Integer(), nullable=True),
        sa.Column("config_key", sa.String(length=255), nullable=False),
        sa.Column("config_value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["integration_service_id"],
            ["integration_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "integration_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("integration_service_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer_integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["integration_service_id"],
            ["integration_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "custom_alert_creation_condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_order_id", sa.Integer(), nullable=True),
        sa.Column("field_name", sa.String(length=1024), nullable=False),
        sa.Column("field_value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_order_id"],
            ["custom_alert_creation_event_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "custom_alert_creation_event_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_order_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("field", sa.String(length=1024), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_order_id"],
            ["custom_alert_creation_event_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "integration_auth_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=True),
        sa.Column("auth_key_name", sa.String(length=255), nullable=False),
        sa.Column("auth_value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["integration_subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "smtp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=1024), nullable=False),
        sa.Column("smtp_password", sa.String(length=256), nullable=False),
        sa.Column("smtp_server", sa.String(length=256), nullable=False),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("smtp")
    op.drop_table("integration_auth_keys")
    op.drop_table("custom_alert_creation_event_config")
    op.drop_table("custom_alert_creation_condition")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_table("integration_subscriptions")
    op.drop_table("integration_configs")
    op.drop_table("customersmeta")
    op.drop_table("custom_alert_creation_event_order")
    op.drop_table("connectorhistory")
    op.drop_table("available_integrations_auth_keys")
    op.drop_index(op.f("ix_agents_agent_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_schedulerjob_next_run_time"), table_name="schedulerjob")
    op.drop_table("schedulerjob")
    op.drop_index(op.f("ix_scheduled_job_metadata_job_id"), table_name="scheduled_job_metadata")
    op.drop_table("scheduled_job_metadata")
    op.drop_table("role")
    op.drop_table("monitoring_alerts")
    op.drop_table("log_entries")
    op.drop_table("license")
    op.drop_table("integration_services")
    op.drop_index(op.f("ix_customers_customer_code"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("customer_provisioning_default_settings")
    op.drop_table("customer_integrations_meta")
    op.drop_table("customer_integrations")
    op.drop_table("custom_alert_creation_settings")
    op.drop_table("connectors")
    op.drop_table("available_integrations")
    # ### end Alembic commands ###
