"""Add Job Description to Job Metadata Table

Revision ID: c3ad5012f4db
Revises: bdf40d064ed1
Create Date: 2024-04-23 14:11:01.313978

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3ad5012f4db"
down_revision: Union[str, None] = "bdf40d064ed1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scheduled_job_metadata", sa.Column("job_description", sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
