"""Add content pack ids network connectors meta table

Revision ID: d05281d02b0f
Revises: 16855d538921
Create Date: 2024-05-01 09:35:17.751914

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d05281d02b0f"
down_revision: Union[str, None] = "16855d538921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_network_connectors_meta", sa.Column("graylog_content_pack_input_id", sa.String(length=1024), nullable=False))
    op.add_column("customer_network_connectors_meta", sa.Column("graylog_content_pack_stream_id", sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_network_connectors_meta", "graylog_content_pack_stream_id")
    op.drop_column("customer_network_connectors_meta", "graylog_content_pack_input_id")
    # ### end Alembic commands ###
