"""Add ai report tables

Revision ID: d0da7a384546
Revises: d000000000000
Create Date: 2026-04-07 11:01:35.704501

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0da7a384546"
down_revision: Union[str, None] = "d000000000000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analyst_job",
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("alert_type", sa.String(length=64), nullable=True),
        sa.Column("triggered_by", sa.String(length=50), nullable=False),
        sa.Column("template_used", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_analyst_job_alert_id"), "ai_analyst_job", ["alert_id"], unique=False)
    op.create_index(op.f("ix_ai_analyst_job_created_at"), "ai_analyst_job", ["created_at"], unique=False)
    op.create_index(op.f("ix_ai_analyst_job_customer_code"), "ai_analyst_job", ["customer_code"], unique=False)
    op.create_index(op.f("ix_ai_analyst_job_status"), "ai_analyst_job", ["status"], unique=False)
    op.create_table(
        "ai_analyst_report",
        sa.Column("report_markdown", mysql.LONGTEXT(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("recommended_actions", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=64), nullable=False),
        sa.Column("severity_assessment", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ai_analyst_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_analyst_report_alert_id"), "ai_analyst_report", ["alert_id"], unique=False)
    op.create_index(op.f("ix_ai_analyst_report_created_at"), "ai_analyst_report", ["created_at"], unique=False)
    op.create_index(op.f("ix_ai_analyst_report_customer_code"), "ai_analyst_report", ["customer_code"], unique=False)
    op.create_index(op.f("ix_ai_analyst_report_job_id"), "ai_analyst_report", ["job_id"], unique=False)
    op.create_table(
        "ai_analyst_ioc",
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=64), nullable=False),
        sa.Column("ioc_value", sa.String(length=512), nullable=False),
        sa.Column("ioc_type", sa.String(length=50), nullable=False),
        sa.Column("vt_verdict", sa.String(length=50), nullable=False),
        sa.Column("vt_score", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_code"],
            ["customers.customer_code"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["ai_analyst_report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_analyst_ioc_alert_id"), "ai_analyst_ioc", ["alert_id"], unique=False)
    op.create_index(op.f("ix_ai_analyst_ioc_created_at"), "ai_analyst_ioc", ["created_at"], unique=False)
    op.create_index(op.f("ix_ai_analyst_ioc_customer_code"), "ai_analyst_ioc", ["customer_code"], unique=False)
    op.create_index(op.f("ix_ai_analyst_ioc_report_id"), "ai_analyst_ioc", ["report_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_analyst_ioc_report_id"), table_name="ai_analyst_ioc")
    op.drop_index(op.f("ix_ai_analyst_ioc_customer_code"), table_name="ai_analyst_ioc")
    op.drop_index(op.f("ix_ai_analyst_ioc_created_at"), table_name="ai_analyst_ioc")
    op.drop_index(op.f("ix_ai_analyst_ioc_alert_id"), table_name="ai_analyst_ioc")
    op.drop_table("ai_analyst_ioc")
    op.drop_index(op.f("ix_ai_analyst_report_job_id"), table_name="ai_analyst_report")
    op.drop_index(op.f("ix_ai_analyst_report_customer_code"), table_name="ai_analyst_report")
    op.drop_index(op.f("ix_ai_analyst_report_created_at"), table_name="ai_analyst_report")
    op.drop_index(op.f("ix_ai_analyst_report_alert_id"), table_name="ai_analyst_report")
    op.drop_table("ai_analyst_report")
    op.drop_index(op.f("ix_ai_analyst_job_status"), table_name="ai_analyst_job")
    op.drop_index(op.f("ix_ai_analyst_job_customer_code"), table_name="ai_analyst_job")
    op.drop_index(op.f("ix_ai_analyst_job_created_at"), table_name="ai_analyst_job")
    op.drop_index(op.f("ix_ai_analyst_job_alert_id"), table_name="ai_analyst_job")
    op.drop_table("ai_analyst_job")
    # ### end Alembic commands ###
