"""Add vuln reports table

Revision ID: d21f0b3329b4
Revises: ea1e223c3d62
Create Date: 2025-12-31 15:06:46.622255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd21f0b3329b4'
down_revision: Union[str, None] = 'ea1e223c3d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerability_reports',
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_reports_customer_code'), 'vulnerability_reports', ['customer_code'], unique=False)
    op.create_index(op.f('ix_vulnerability_reports_generated_at'), 'vulnerability_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_vulnerability_reports_status'), 'vulnerability_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_reports_status'), table_name='vulnerability_reports')
    op.drop_index(op.f('ix_vulnerability_reports_generated_at'), table_name='vulnerability_reports')
    op.drop_index(op.f('ix_vulnerability_reports_customer_code'), table_name='vulnerability_reports')
    op.drop_table('vulnerability_reports')
    # ### end Alembic commands ###
