"""Add agent vulnerabilities table

Revision ID: dd0e62747e2c
Revises: 6796a7d001ad
Create Date: 2025-09-09 14:52:29.588326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd0e62747e2c'
down_revision: Union[str, None] = '6796a7d001ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('references', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('remediated_at', sa.DateTime(), nullable=True),
    sa.Column('epss_score', sa.String(length=50), nullable=True),
    sa.Column('epss_percentile', sa.String(length=50), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_vulnerabilities_agent_id'), 'agent_vulnerabilities', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_vulnerabilities_cve_id'), 'agent_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_agent_vulnerabilities_discovered_at'), 'agent_vulnerabilities', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_agent_vulnerabilities_severity'), 'agent_vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_agent_vulnerabilities_status'), 'agent_vulnerabilities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_vulnerabilities_status'), table_name='agent_vulnerabilities')
    op.drop_index(op.f('ix_agent_vulnerabilities_severity'), table_name='agent_vulnerabilities')
    op.drop_index(op.f('ix_agent_vulnerabilities_discovered_at'), table_name='agent_vulnerabilities')
    op.drop_index(op.f('ix_agent_vulnerabilities_cve_id'), table_name='agent_vulnerabilities')
    op.drop_index(op.f('ix_agent_vulnerabilities_agent_id'), table_name='agent_vulnerabilities')
    op.drop_table('agent_vulnerabilities')
    # ### end Alembic commands ###
