"""update ai review tables

Revision ID: e01d1d2600eb
Revises: f75a3f9bb316
Create Date: 2026-04-22 12:22:29.708523

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e01d1d2600eb"
down_revision: Union[str, None] = "f75a3f9bb316"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_analyst_review", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint("uq_ai_analyst_review_report_reviewer", "ai_analyst_review", ["report_id", "reviewer_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ai_analyst_review_report_reviewer", "ai_analyst_review", type_="unique")
    op.drop_column("ai_analyst_review", "updated_at")
    # ### end Alembic commands ###
