"""Add logo_base64 column

Revision ID: e74210501112
Revises: 74727b1f75e6
Create Date: 2025-11-29 09:30:00.832420

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e74210501112"
down_revision: Union[str, None] = "74727b1f75e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_portal_settings", sa.Column("logo_base64", mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_portal_settings", "logo_base64")
    # ### end Alembic commands ###
