"""Add assigned to and case meta

Revision ID: e90f3760fa40
Revises: ba98bd0e3967
Create Date: 2024-07-15 18:07:45.012570

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e90f3760fa40"
down_revision: Union[str, None] = "ba98bd0e3967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_management_alert", sa.Column("assigned_to", sa.String(length=50), nullable=True))
    op.add_column("incident_management_case", sa.Column("case_creation_time", sa.DateTime(), nullable=False))
    op.add_column("incident_management_case", sa.Column("case_status", sa.String(length=50), nullable=False))
    op.add_column("incident_management_case", sa.Column("assigned_to", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_management_case", "assigned_to")
    op.drop_column("incident_management_case", "case_status")
    op.drop_column("incident_management_case", "case_creation_time")
    op.drop_column("incident_management_alert", "assigned_to")
    # ### end Alembic commands ###
