"""Add case closed time column

Revision ID: ea1e223c3d62
Revises: e74210501112
Create Date: 2025-12-16 09:29:33.243448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ea1e223c3d62'
down_revision: Union[str, None] = 'e74210501112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_management_case', sa.Column('case_closed_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_management_case', 'case_closed_time')
    # ### end Alembic commands ###
