"""Add grafana datasource uid to network connectors meta table

Revision ID: ec63589cc24d
Revises: d05281d02b0f
Create Date: 2024-05-01 11:05:15.935826

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec63589cc24d"
down_revision: Union[str, None] = "d05281d02b0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_network_connectors_meta", sa.Column("grafana_datasource_uid", sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_network_connectors_meta", "grafana_datasource_uid")
    # ### end Alembic commands ###
