"""Add ai review tables

Revision ID: f75a3f9bb316
Revises: 41a7b41cd83a
Create Date: 2026-04-22 11:19:24.303540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f75a3f9bb316'
down_revision: Union[str, None] = '41a7b41cd83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyst_review',
    sa.Column('missing_steps', sa.Text(), nullable=True),
    sa.Column('suggested_edits', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('overall_verdict', sa.String(length=4), nullable=True),
    sa.Column('template_choice', sa.String(length=7), nullable=True),
    sa.Column('template_used', sa.String(length=128), nullable=True),
    sa.Column('rating_instructions', sa.Integer(), nullable=True),
    sa.Column('rating_artifacts', sa.Integer(), nullable=True),
    sa.Column('rating_severity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.ForeignKeyConstraint(['report_id'], ['ai_analyst_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyst_review_alert_id'), 'ai_analyst_review', ['alert_id'], unique=False)
    op.create_index(op.f('ix_ai_analyst_review_created_at'), 'ai_analyst_review', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyst_review_customer_code'), 'ai_analyst_review', ['customer_code'], unique=False)
    op.create_index(op.f('ix_ai_analyst_review_report_id'), 'ai_analyst_review', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_analyst_review_reviewer_user_id'), 'ai_analyst_review', ['reviewer_user_id'], unique=False)
    op.create_table('ai_analyst_ioc_review',
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.Column('verdict_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['ai_analyst_ioc.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['ai_analyst_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyst_ioc_review_created_at'), 'ai_analyst_ioc_review', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyst_ioc_review_ioc_id'), 'ai_analyst_ioc_review', ['ioc_id'], unique=False)
    op.create_index(op.f('ix_ai_analyst_ioc_review_review_id'), 'ai_analyst_ioc_review', ['review_id'], unique=False)
    op.create_table('ai_analyst_palace_lesson',
    sa.Column('lesson_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('lesson_type', sa.String(length=20), nullable=False),
    sa.Column('durability', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.ForeignKeyConstraint(['review_id'], ['ai_analyst_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyst_palace_lesson_created_at'), 'ai_analyst_palace_lesson', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyst_palace_lesson_customer_code'), 'ai_analyst_palace_lesson', ['customer_code'], unique=False)
    op.create_index(op.f('ix_ai_analyst_palace_lesson_review_id'), 'ai_analyst_palace_lesson', ['review_id'], unique=False)
    op.create_index(op.f('ix_ai_analyst_palace_lesson_status'), 'ai_analyst_palace_lesson', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyst_palace_lesson_status'), table_name='ai_analyst_palace_lesson')
    op.drop_index(op.f('ix_ai_analyst_palace_lesson_review_id'), table_name='ai_analyst_palace_lesson')
    op.drop_index(op.f('ix_ai_analyst_palace_lesson_customer_code'), table_name='ai_analyst_palace_lesson')
    op.drop_index(op.f('ix_ai_analyst_palace_lesson_created_at'), table_name='ai_analyst_palace_lesson')
    op.drop_table('ai_analyst_palace_lesson')
    op.drop_index(op.f('ix_ai_analyst_ioc_review_review_id'), table_name='ai_analyst_ioc_review')
    op.drop_index(op.f('ix_ai_analyst_ioc_review_ioc_id'), table_name='ai_analyst_ioc_review')
    op.drop_index(op.f('ix_ai_analyst_ioc_review_created_at'), table_name='ai_analyst_ioc_review')
    op.drop_table('ai_analyst_ioc_review')
    op.drop_index(op.f('ix_ai_analyst_review_reviewer_user_id'), table_name='ai_analyst_review')
    op.drop_index(op.f('ix_ai_analyst_review_report_id'), table_name='ai_analyst_review')
    op.drop_index(op.f('ix_ai_analyst_review_customer_code'), table_name='ai_analyst_review')
    op.drop_index(op.f('ix_ai_analyst_review_created_at'), table_name='ai_analyst_review')
    op.drop_index(op.f('ix_ai_analyst_review_alert_id'), table_name='ai_analyst_review')
    op.drop_table('ai_analyst_review')
    # ### end Alembic commands ###
