"""Add github audit tables

Revision ID: fb51d610b306
Revises: 72635705c067
Create Date: 2026-02-09 13:20:39.267397

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb51d610b306"
down_revision: Union[str, None] = "72635705c067"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_audit_config",
        sa.Column("repo_filter_list", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("github_token", sa.String(length=500), nullable=False),
        sa.Column("organization", sa.String(length=100), nullable=False),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_audit_enabled", sa.Boolean(), nullable=False),
        sa.Column("audit_schedule_cron", sa.String(length=50), nullable=True),
        sa.Column("include_repos", sa.Boolean(), nullable=False),
        sa.Column("include_workflows", sa.Boolean(), nullable=False),
        sa.Column("include_members", sa.Boolean(), nullable=False),
        sa.Column("include_archived_repos", sa.Boolean(), nullable=False),
        sa.Column("repo_filter_mode", sa.String(length=20), nullable=False),
        sa.Column("notify_on_critical", sa.Boolean(), nullable=False),
        sa.Column("notify_on_high", sa.Boolean(), nullable=False),
        sa.Column("notification_webhook_url", sa.String(length=500), nullable=True),
        sa.Column("notification_email", sa.String(length=255), nullable=True),
        sa.Column("minimum_passing_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("last_audit_at", sa.DateTime(), nullable=True),
        sa.Column("last_audit_score", sa.Float(), nullable=True),
        sa.Column("last_audit_grade", sa.String(length=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_github_audit_config_customer_code"), "github_audit_config", ["customer_code"], unique=False)
    op.create_table(
        "github_audit_check_exclusion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("check_id", sa.String(length=100), nullable=False),
        sa.Column("resource_name", sa.String(length=255), nullable=True),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("reason", sa.String(length=1024), nullable=False),
        sa.Column("approved_by", sa.String(length=100), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["github_audit_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_github_audit_check_exclusion_config_id"), "github_audit_check_exclusion", ["config_id"], unique=False)
    op.create_index(op.f("ix_github_audit_check_exclusion_customer_code"), "github_audit_check_exclusion", ["customer_code"], unique=False)
    op.create_table(
        "github_audit_report",
        sa.Column("full_report", sa.JSON(), nullable=True),
        sa.Column("top_findings", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("report_name", sa.String(length=255), nullable=False),
        sa.Column("organization", sa.String(length=100), nullable=False),
        sa.Column("audit_started_at", sa.DateTime(), nullable=False),
        sa.Column("audit_completed_at", sa.DateTime(), nullable=True),
        sa.Column("audit_duration_seconds", sa.Float(), nullable=True),
        sa.Column("total_repos_audited", sa.Integer(), nullable=False),
        sa.Column("total_checks", sa.Integer(), nullable=False),
        sa.Column("passed_checks", sa.Integer(), nullable=False),
        sa.Column("failed_checks", sa.Integer(), nullable=False),
        sa.Column("warning_checks", sa.Integer(), nullable=False),
        sa.Column("critical_findings", sa.Integer(), nullable=False),
        sa.Column("high_findings", sa.Integer(), nullable=False),
        sa.Column("medium_findings", sa.Integer(), nullable=False),
        sa.Column("low_findings", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("grade", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column("triggered_by", sa.String(length=50), nullable=False),
        sa.Column("triggered_by_user", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["github_audit_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_github_audit_report_config_id"), "github_audit_report", ["config_id"], unique=False)
    op.create_index(op.f("ix_github_audit_report_customer_code"), "github_audit_report", ["customer_code"], unique=False)
    op.create_table(
        "github_audit_baseline",
        sa.Column("expected_checks", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("baseline_report_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_report_id"],
            ["github_audit_report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["github_audit_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_github_audit_baseline_config_id"), "github_audit_baseline", ["config_id"], unique=False)
    op.create_index(op.f("ix_github_audit_baseline_customer_code"), "github_audit_baseline", ["customer_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_github_audit_baseline_customer_code"), table_name="github_audit_baseline")
    op.drop_index(op.f("ix_github_audit_baseline_config_id"), table_name="github_audit_baseline")
    op.drop_table("github_audit_baseline")
    op.drop_index(op.f("ix_github_audit_report_customer_code"), table_name="github_audit_report")
    op.drop_index(op.f("ix_github_audit_report_config_id"), table_name="github_audit_report")
    op.drop_table("github_audit_report")
    op.drop_index(op.f("ix_github_audit_check_exclusion_customer_code"), table_name="github_audit_check_exclusion")
    op.drop_index(op.f("ix_github_audit_check_exclusion_config_id"), table_name="github_audit_check_exclusion")
    op.drop_table("github_audit_check_exclusion")
    op.drop_index(op.f("ix_github_audit_config_customer_code"), table_name="github_audit_config")
    op.drop_table("github_audit_config")
    # ### end Alembic commands ###
