{
 "title": "FORTINET - UTM LOGS APP CONTROL",
 "description": "FORTINET - UTM LOGS",
 "tags": [ "FORTINET UTM" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters", "label": "Filters" },
   {
    "name": "firewall",
    "label": "Firewall",
    "query": "{ \"find\": \"terms\", \"field\": \"devname\", \"query\": \"type:utm AND subtype:app\"}"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"syslog_level\", \"query\": \"type:utm AND subtype:app\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "UTM EVENTS - APP CONTROL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL: FIREWALLS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1y" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "devname", "id": "1", "type": "cardinality" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY FIREWALL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "devname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY FIREWALL",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "devname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY CATEGORY",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "appcat",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY FIREWALL - HISTOGRAM (TOP 20)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "devname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "5m", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY SEVERITY",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syslog_level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY ACTION",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APP CONTROL BY FIREWALL AND THREAT TYPE",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "devname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "field": "action",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APPs BLOCKED (TOP 10)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "app",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity AND action:block",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APPs BLOCKED BY CATEGORY",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "appcat",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND action:block AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "UTM EVENTS - APPs BLOCKED BY USER ACCOUNT",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND action:block AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FIREWALL EVENTS",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      { "type": "date_histogram", "id": "1", "settings": { "interval": "auto" } }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "type:utm AND subtype:app AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}