{
 "title": "FORTINET - VPN LOGS",
 "description": "FORTINET - VPN LOGS",
 "tags": [ "FORTINET UTM" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters", "label": "Filters" },
   {
    "name": "firewall",
    "label": "Firewall",
    "query": "{ \"find\": \"terms\", \"field\": \"devname\", \"query\": \"type:event AND subtype:vpn\"}"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"syslog_level\", \"query\": \"type:event AND subtype:vpn\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "VPN SUMMARY (SDWAN + FORTICLIENT)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "VPN EVENTS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN FAILED AUTHs (FORTICLIENT)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity AND action:\"ssl-login-fail\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS: FIREWALLS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "365d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "devname", "id": "1", "type": "cardinality" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS BY FIREWALL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "devname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS BY FIREWALL",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "devname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS BY SEVERITY",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syslog_level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS BY VPN TYPE",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tunneltype",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS BY VPN TYPE",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tunneltype",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPN LOGS BY STATUS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "msg",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDWAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "SDWAN EVENTS",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SDWAN - VPN LOGS BY ACTION",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 4, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "action",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SDWAN - VPN LOGS BY FIREWALL - HISTOGRAM (TOP 20)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "devname",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "5m", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SDWAN - REMOTE IP GeoIP",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "remip_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SDWAN - REMOTE IP AND GeoIP",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "remip_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "remip",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SDWAN - REMOTE GeoIP AND ACTION",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 26 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "remip_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "action",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "SDWAN EVENTS",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:ipsec AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "FORTICLIENT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "FORTICLIENT EVENTS",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "VPN FAILED AUTHs (FORTICLIENT)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity AND action:\"ssl-login-fail\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT - FAILED AUTHs BY USER",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "user",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND devname:$firewall AND syslog_level:$severity AND action:\"ssl-login-fail\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT - USER AND DURATION",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "user",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "duration",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT - REMOTE IP GeoIP",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "remip_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT - REMOTE IP AND GeoIP",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "remip_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "remip",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT - REMOTE GeoIP AND USER",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "remip_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "user",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "UTM EVENTS - VPN LOGS EVENTS BY USER (TOP 10)",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "user",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT - VPN TRAFFIC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "BYTES RCVD",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "rcvdbyte", "id": "1", "type": "avg" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      },
      {
       "alias": "BYTES SENT",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "sentbyte", "id": "1", "type": "avg" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "FORTICLIENT EVENTS",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "type:event AND subtype:vpn AND tunneltype:\"ssl-tunnel\" AND devname:$firewall AND syslog_level:$severity",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}