{
 "title": "EDR - SENTINELONE EPP - _SUMMARY",
 "tags": [ "EDR" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "eventSeverity",
    "label": "Event Severity",
    "query": "{ \"find\": \"terms\", \"field\": \"eventSeverity\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "THREATS CLASSIFICATION",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_threatClassification",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY POLICY GROUP",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_group",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY CATEGOTY",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cat",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_computerName",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "data_computerName",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 AGENTS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_computerName",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS (TOTAL)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SECURITY EVENTS BY ALERT LEVEL",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "eventSeverity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS SEVERITY - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "eventSeverity",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SECURITY EVENTS BY CATEGORY",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "cat",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SECURITY EVENTS BY SITE",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "siteName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FILE PATHS",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "data_filePath",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY GROUP",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:332",
       "field": "data_groupName",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:330",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY ALERT GROUP (TOP 10) - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_groupName",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "eventSeverity:$eventSeverity",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}