{
 "title": "DUO AUTH LOGS",
 "tags": [ "EDR" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"rule_groups:rootcheck OR rule_groups:oscap OR rule_groups:sca\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "DUO EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:183",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:181", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY ACCOUNT",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:65",
       "fake": true,
       "field": "user_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:63", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY TYPE",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:206",
       "fake": true,
       "field": "factor",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:204", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY ACCESS DEVICE",
   "type": "table",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:65",
       "fake": true,
       "field": "access_device_hostname",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:63", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "!access_device_hostname:null",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 ACCOUNTS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCESS DEVICE GeoIP",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "access_device_location_country",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY AUTH DEVICE",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:65",
       "fake": true,
       "field": "auth_device_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:63", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "!auth_device_name:null",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTH DEVICE GeoIP",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "auth_device_location_country",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "RESULTS",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:493",
       "fake": true,
       "field": "result",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": "N/A",
        "order": "desc",
        "orderBy": "_term",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:494",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:491",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS DENIED",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:493",
       "fake": true,
       "field": "user_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:491",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "result:denied",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS DENIED (ACCESS DEVICE)",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:493",
       "fake": true,
       "field": "access_device_hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:491",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "result:denied AND !access_device_hostname:null",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS DENIED (AUTH DEVICE)",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:493",
       "fake": true,
       "field": "auth_device_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:491",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "result:denied AND !auth_device_name:null",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DUO EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      { "type": "date_histogram", "id": "1", "settings": { "interval": "auto" } }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}