export const ICONS = {
	dashboard: "carbon:dashboard",
	agents: "carbon:network-3",
	customers: "carbon:user-avatar",
	agent: "carbon:cloud-monitoring",
	packages: "carbon:package",
	ports: "carbon:ip",
	processes: "carbon:activity",
	vulnerabilities: "carbon:security",
	alerts: "carbon:warning-hex",
	cases: "carbon:ibm-secure-infrastructure-on-vpc-for-regulated-industries",
	chatbot: "carbon:ai-generate",
	system: "carbon:settings",
	collectors: "carbon:chip",
	tasks: "carbon:task",
	monitoring: "carbon:analytics",
	celery: "carbon:bee",
	websocket: "carbon:ibm-watson-discovery",
	worker: "carbon:ibm-openshift-container-platform-on-vpc-for-regulated-industries",
	eventSearch: "carbon:search-locate",
	reports: "carbon:document-pdf"
}
