{
 "title": "SAP - USERS AUTH",
 "tags": [ "SAP" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "log_source",
    "label": "LOG SOURCE",
    "query": "{ \"find\": \"terms\", \"field\": \"logSource\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "AUTH ERRORS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "event_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:errCode AND logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY ERROR (Top 10)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "errDetails",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:errCode AND logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY ERROR (Top 10)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "errDetails",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FAILED AUTH EVENTS BY COUNTRY",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ip_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT errCode:0 AND logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 USERS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "params_loginID",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SAP - TOTAL ACCOUNTS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "params_loginID", "id": "1", "type": "cardinality" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USER AGENTS",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "userAgent_raw",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALL AUTH EVENTS BY COUNTRY",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ip_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FAILED AUTHS BY ACCOUNT AND ERROR",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "params_loginID",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "errDetails",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ip_country_code",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:errCode AND logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      { "type": "date_histogram", "id": "1", "settings": { "interval": "auto" } }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "logSource:$log_source",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}