{
 "title": "MIMECAST OVERVIEW",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "SUMMARY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:135",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:133", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 SENDERS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "Sender",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 RECEIVERS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:211",
         "fake": true,
         "field": "Rcpt",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "Unknown",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:117",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 RECEIVERS",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:211",
         "fake": true,
         "field": "Rcpt",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "Unknown",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "MAIL FLOWS",
     "type": "netsage-sankey-panel",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Sender",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Rcpt",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 IPs",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "IP",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "IP_country_code",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 GEO IPs",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 27 },
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "IP_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 SPAM SCORES",
     "type": "table",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "SpamScore",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "MAIL DIRECTION",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "Dir",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "type",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "SPAM PROC INFO",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "SpamProcessingDetail",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "type",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "MIMECAST LOGS",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
       ],
       "timeField": "datetime"
      }
     ]
    }
   ]
  },
  {
   "title": "VIRUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "VIRUS EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:135",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:133", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 SENDERS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "Sender",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 RECEIVERS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:211",
         "fake": true,
         "field": "Rcpt",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "Unknown",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:117",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 RECEIVERS",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:211",
         "fake": true,
         "field": "Recipient",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "Unknown",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 DOMAIN SENDERS",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "SenderDomain",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 IPs",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "IP",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "IP_country_code",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 GEO IPs",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "IP_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "VIRUS FILE NAMES",
     "type": "netsage-sankey-panel",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Virus",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Sender",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "Virus:*",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "VIRUS LOGS",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
       ],
       "query": "Virus:*",
       "timeField": "datetime"
      }
     ]
    }
   ]
  },
  {
   "title": "SPAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SPAM EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:135",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:133", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 SENDERS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "Sender",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 RECEIVERS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:211",
         "fake": true,
         "field": "Rcpt",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "Unknown",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "$$hashKey": "object:117",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 RECEIVERS",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:211",
         "fake": true,
         "field": "Rcpt",
         "id": "3",
         "settings": {
          "min_doc_count": "1",
          "missing": "Unknown",
          "order": "desc",
          "orderBy": "_count",
          "size": "10"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 SUBJECTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "Subject",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 IPs",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:89",
         "fake": true,
         "field": "IP",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "IP_country_code",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "TOP 10 GEO IPs",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "IP_country_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "SPAM SUBJECTS",
     "type": "netsage-sankey-panel",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Sender",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "Subject",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    },
    {
     "title": "SPAM LOGS",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
       ],
       "query": "SpamScore:*",
       "timeField": "datetime"
      }
     ]
    }
   ]
  },
  { "title": "URL SCANNING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "URL SCAN EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:135",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:133", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 SENDERS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:89",
       "fake": true,
       "field": "fromUserEmailAddress",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fromUserEmailAddress:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 RECEIVERS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:211",
       "fake": true,
       "field": "userEmailAddress",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "Unknown",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:117",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 RECEIVERS",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:211",
       "fake": true,
       "field": "userEmailAddress",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "Unknown",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 SUBJECTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:89",
       "fake": true,
       "field": "subject",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "scanResult",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 MALICIOUS URLS",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:89",
       "fake": true,
       "field": "url",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "sendingIp",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:87", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "scanResult:malicious",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 GEO IPs",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sendingIp_country_code",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EMAIL SUBJECTS WITH URLS",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fromUserEmailAddress",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "subject",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "URL LOGS",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "scanResult:*",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}