{
 "title": "O365 - ACTIVE DIRECTORY",
 "tags": [ "O365" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "operation",
    "label": "Operation",
    "query": "{ \"find\": \"terms\", \"field\": \"data_office365_Operation\", \"query\": \"data_office365_Workload:AzureActiveDirectory\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_level:>=12 AND data_office365_Operation:$operation",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY OPERATION (Top 10)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_Operation",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data_office365_CreationTime",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY OPERATION",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_Operation",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DEVICE EVENTS (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:\"Add device.\" OR data_office365_Operation:\"Add registered owner to device.\" OR data_office365_Operation:\"Add registered users to device.\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DEVICE EVENTS BY OPERATION",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_Operation",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:\"Add device.\" OR data_office365_Operation:\"Add registered owner to device.\" OR data_office365_Operation:\"Add registered users to device.\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS ADDED EVENTS (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:\"Add user.\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS ADDED EVENTS (Results)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ResultStatus",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data_office365_CreationTime",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:\"Add user.\" AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS ADDED EVENTS (Results)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ResultStatus",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:\"Add user.\" AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS ADDED EVENTS (Accounts)",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ObjectId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data_office365_ResultStatus",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:\"Add user.\" AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EXTERNAL USERS LOGIN (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND (data_office365_UserId:*#EXT# OR data_office365_UserId:*gmail.com)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EXTERNAL USERS LOGIN (Results)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ResultStatus",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND (data_office365_UserId:*#EXT# OR data_office365_UserId:*gmail.com) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EXTERNAL USERS LOGIN (Accounts)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_UserId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data_office365_ResultStatus",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND (data_office365_UserId:*#EXT# OR data_office365_UserId:*gmail.com) AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS LOGGEDIN NON MFA (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND data_office365_ResultStatus:Success AND data_office365_ExtendedProperties_UserAuthenticationMethod:1",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS LOGGEDIN NON MFA (Accounts)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_UserId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data_office365_ResultStatus",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND data_office365_ResultStatus:Success AND data_office365_ExtendedProperties_UserAuthenticationMethod:1",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS NON TRUSTED SOURCE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND !data_office365_ActorIpAddress_country_code:COMPANY_COUNTRY_CODE",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS NON TRUSTED SOURCE BY COUNTRY",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 10, "x": 4, "y": 21 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ActorIpAddress_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND !data_office365_ActorIpAddress_country_code:COMPANY_COUNTRY_CODE",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS NON TRUSTED SOURCE BY ACCOUNT",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_UserId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data_office365_ActorIpAddress",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data_office365_ActorIpAddress_country_code",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND !data_office365_ActorIpAddress_country_code:COMPANY_COUNTRY_CODE",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHS NON TRUSTED - ACCOUNTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data_office365_UserId", "id": "1", "type": "cardinality" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND !data_office365_ActorIpAddress_country_code:COMPANY_COUNTRY_CODE",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MAX SEVERITY (0 - 15)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rule_level",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "data_office365_Operation:$operation",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 OPERATIONS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_office365_Operation",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "data_office365_CreationTime", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS (Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AZURE AD - FAILED AUTHS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoginFailed AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AZURE AD - ALL AUTH EVENTS BY COUNTRY",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 48 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ActorIpAddress_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:AzureActiveDirectory AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FAILED AUTHS BY ACCOUNT AND ERROR",
   "type": "table",
   "gridPos": { "h": 32, "w": 10, "x": 14, "y": 48 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_UserId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data_office365_LogonError",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data_office365_ActorIpAddress_country_code",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoginFailed AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AZURE AD - TOTAL AUTHS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND  rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FAILED AUTHS BY ERROR (Top 15)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_office365_LogonError",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SUCCESSFUL AUTHS BY USER AGENT (Top 15)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_office365_ExtendedProperties_UserAgent",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:UserLoggedIn AND data_office365_ResultStatus:Success",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}