{
 "title": "O365 - MICROSOFT FORMS",
 "tags": [ "O365" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "operation",
    "label": "Operation",
    "query": "{ \"find\": \"terms\", \"field\": \"data_office365_Operation\", \"query\": \"data_office365_Workload:MicrosoftForms\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_level\", \"query\": \"data_office365_Workload:MicrosoftForms\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_level:>=12 AND data_office365_Operation:$operation AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY OPERATION (Top 10)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_Operation",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data_office365_CreationTime",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY OPERATION",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_Operation",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY APP",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_SourceApp",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MAX SEVERITY (0 - 15)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rule_level",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "data_office365_Operation:$operation AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 OPERATIONS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_office365_Operation",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS (Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MS-FORMS EVENTS BY FORM NAME",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_FormName",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MS-FORMS - ALL EVENTS BY SRC COUNTRY",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_ClientIP_country_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:MicrosoftForms AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MS-FORMS EVENTS BY ACCOUNT",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_office365_UserId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data_office365_ClientIP_country_code",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "data_office365_Operation:$operation AND rule_level:$rule_level AND data_office365_Workload:MicrosoftForms",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}