{
 "title": "O365 - MITRE ATT&CK",
 "tags": [ "O365" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters", "label": "Filters" },
   {
    "name": "workload",
    "label": "WORKLOAD",
    "query": "{ \"find\": \"terms\", \"field\": \"data_office365_Workload\", \"query\": \"_exists_:rule_mitre_tactic\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "MITRE ATT&CK EBRICHMENT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "MITRE ENRICHED EVENTS",
     "bucketAggs": [
      {
       "$$hashKey": "object:266",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:264", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:rule_mitre_id AND data_office365_Workload:$workload AND rule_level:$rule_level",
     "timeField": "timestamp"
    },
    {
     "alias": "ALL EVENTS",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK ALERTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:266",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:264", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_level:>=12 AND _exists_:rule_mitre_tactic AND data_office365_Workload:$workload",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNTS AFFECTED",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:161",
       "field": "data_office365_ActorUserId",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:159",
       "field": "data_office365_ActorUserId",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rule_level:>=12 AND _exists_:rule_mitre_tactic AND data_office365_Workload:$workload",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS/ACCOUNTS AFFECTED",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:228",
       "field": "data_office365_ActorUserId",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:226",
       "field": "data_office365_ActorUserId",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rule_level:>=12 AND _exists_:rule_mitre_tactic AND data_office365_Workload:$workload",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "WORKLOADS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:188",
       "fake": true,
       "field": "data_office365_Workload",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:189",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:186", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:rule_mitre_tactic AND data_office365_Workload:$workload AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TACTICS (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:82",
       "fake": true,
       "field": "rule_mitre_tactic",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:83",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TACTICS",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 5, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:615",
       "fake": true,
       "field": "rule_mitre_tactic",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES",
   "type": "table",
   "gridPos": { "h": 22, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:615",
       "fake": true,
       "field": "rule_mitre_id",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND _exists_:rule_mitre_tactic AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:82",
       "fake": true,
       "field": "rule_mitre_technique",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:83",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND _exists_:rule_mitre_tactic AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 5, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:615",
       "fake": true,
       "field": "rule_mitre_technique",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND _exists_:rule_mitre_tactic AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - TOP 10 ACCOUNTS",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:82",
       "fake": true,
       "field": "data_office365_UserId",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND _exists_:rule_mitre_tactic AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 OPERATIONS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_office365_Operation",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office365_Workload:$workload AND _exists_:rule_mitre_tactic AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - TELEMETRY",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      { "type": "date_histogram", "id": "1", "settings": { "interval": "auto" } }
     ],
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "data_office365_Workload:$workload AND _exists_:rule_mitre_tactic AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}