from datetime import datetime
from enum import Enum
from types import UnionType
from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Union
from typing import get_args
from typing import get_origin

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import model_validator


class ValidSyslogType(str, Enum):
    WAZUH = "wazuh"


class CreateAlertRequest(BaseModel):
    index_name: str = Field(
        ...,
        description="The name of the index to search alerts for.",
    )
    alert_id: str = Field(..., description="The alert id.")


class CreateAlertRequestRoute(BaseModel):
    index_name: str = Field(
        ...,
        description="The name of the index to search alerts for.",
    )
    index_id: str = Field(..., description="The index id.")
    agent_id: Optional[str] = Field(
        None,
        description="The agent id.",
    )
    alert_id: Optional[int] = Field(
        None,
        description="The alert id.",
    )


class CreateAlertResponse(BaseModel):
    success: bool
    message: str
    alert_id: int = Field(..., description="The alert id as created in CoPilot.")


# class AutoCreateAlertResponse(BaseModel):
#     success: bool
#     message: str


class AutoCreateAlertResponse(BaseModel):
    success: bool
    message: str
    alerts_created: int = 0
    alerts_failed: int = 0
    batches_processed: int = 0
    alerts_remaining: int = 0
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "success": True,
                "message": "Processed 5 batches: 487 alerts created, 13 failed. 2000 alerts remaining for next run",
                "alerts_created": 487,
                "alerts_failed": 13,
                "batches_processed": 5,
                "alerts_remaining": 2000,
            },
        },
    )


class IndexNamesResponse(BaseModel):
    index_names: List[str]
    success: bool
    message: str


class FieldNames(BaseModel):
    field_names: List[str]
    asset_name: str
    timefield_name: str
    alert_title_name: str
    ioc_field_names: Optional[List[str]] = None


def _is_string_field(annotation: Any) -> bool:
    """True for a field declared `str` or `Optional[str]`."""
    if annotation is str:
        return True
    if get_origin(annotation) in (Union, UnionType):
        return str in get_args(annotation)
    return False


class GenericSourceModel(BaseModel):
    timestamp: str = Field(..., description="The timestamp of the alert.")
    timestamp_utc: Optional[str] = Field(
        None,
        description="The UTC timestamp of the alert.",
    )
    rule_description: Optional[str] = Field(
        "No autogenerated rule_description found",
        description="The timefield of the alert to be used when creating the IRIS alert.",
    )
    syslog_level: Optional[str] = Field(
        "No autogenerated syslog_level found",
        description="The timefield of the alert to be used when creating the IRIS alert.",
    )
    syslog_type: Optional[str] = Field(
        None,
        description="The timefield of the alert to be used when creating the IRIS alert.",
    )
    process_id: Optional[str] = Field(
        None,
        description="The process id of the alert.",
    )
    agent_name: Optional[str] = Field(
        None,
        description="The agent name of the alert.",
    )
    model_config = ConfigDict(extra="allow")

    @model_validator(mode="before")
    @classmethod
    def _stringify_numeric_values(cls, data: Any) -> Any:
        """Accept a number where a string field is declared.

        These models are built straight from raw indexer documents, and what a
        source puts in a given field is not ours to control: `timestamp_utc`
        arrives as epoch milliseconds from some pipelines, `syslog_level` as a
        numeric severity, `process_id` as an int. Pydantic 1 coerced all of that
        to `str` silently; Pydantic 2 rejects it with `string_type`, and because
        `get_single_alert_details` turns any exception into a 400, a single
        numeric field stopped the alert being created at all — permanently, since
        the Graylog event is only stamped after a successful create, so the same
        document was retried and re-failed on every scheduler run (#1096).

        Coercing here rather than widening the annotations keeps the rest of the
        ingest path working with plain strings. Driven off the declared fields so
        a string field added later is covered without a second look.

        `bool` is excluded deliberately: it is an `int` subclass in Python, and
        turning `True` into `"True"` would be a silent data change rather than a
        format fix.
        """
        if not isinstance(data, dict):
            return data

        coerced = None
        for name, field in cls.model_fields.items():
            if name not in data or not _is_string_field(field.annotation):
                continue
            value = data[name]
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                continue
            if coerced is None:
                # Copy on first hit — the caller's document is not ours to mutate.
                coerced = dict(data)
            coerced[name] = str(value)

        return coerced if coerced is not None else data

    def to_dict(self):
        return self.model_dump(exclude_none=True)


class GenericAlertModel(BaseModel):
    # NOTE: Pydantic 2 treats names with a leading underscore as PrivateAttr
    # and silently drops them from input parsing. Elasticsearch hits use
    # `_index`, `_id`, `_version`, `_source` as JSON keys, so we expose those
    # via aliases and access them as `index`/`id`/`version`/`source` in code.
    index: str = Field(alias="_index")
    id: str = Field(alias="_id")
    version: int = Field(alias="_version")
    source: GenericSourceModel = Field(alias="_source")
    asset_type_id: Optional[int] = Field(
        None,
        description="The asset type id of the alert which is needed for when we add the asset to IRIS.",
    )
    ioc_value: Optional[str] = Field(
        None,
        description="The IoC value of the alert which is needed for when we add the IoC to IRIS.",
    )
    ioc_type: Optional[str] = Field(
        None,
        description="The IoC type of the alert which is needed for when we add the IoC to IRIS.",
    )
    time_field: Optional[str] = Field(
        "timestamp",
        description="The timefield of the alert to be used when creating the IRIS alert.",
    )
    syslog_type: Optional[str] = Field(
        None,
        description="The type of the alert to be used when creating the CoPilot alert.",
    )
    model_config = ConfigDict(extra="allow", populate_by_name=True)


class AlertDetailsResponse(BaseModel):
    alert_details: GenericAlertModel
    success: bool
    message: str


class CreatedAlertPayload(BaseModel):
    alert_context_payload: dict
    asset_payload: str
    timefield_payload: str
    alert_title_payload: str
    ioc_payload: Optional[dict] = None
    source: str
    index_name: Optional[str] = None
    index_id: Optional[str] = None
    alert_id: Optional[int] = None
    # Wazuh rule level (1-15) surfaced by default plus a normalized severity label
    # so downstream Shuffle consumers don't need custom mapping logic. Issue #980.
    rule_level: Optional[int] = None
    severity: Optional[str] = None


class CreatedCaseNotificationPayload(BaseModel):
    case_name: str
    case_description: str
    case_creation_time: datetime
    alerts: List[CreatedAlertPayload]


class AlertTimelineResponse(BaseModel):
    alert_timeline: List[Dict[str, Any]]
    success: bool
    message: str
