"""Added sublime alerts and SMTP Config

Revision ID: 16a3bb6544b1
Revises: 0381c0088cbe
Create Date: 2023-07-12 17:24:56.551223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a3bb6544b1'
down_revision = '0381c0088cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('smtp_server', sa.String(length=100), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sublime_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sublime_alerts')
    op.drop_table('email_credentials')
    # ### end Alembic commands ###
