"""Add

Revision ID: 26d24321c4c5
Revises: 8b3946f83ac5
Create Date: 2023-07-17 10:54:02.156039

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26d24321c4c5"
down_revision = "8b3946f83ac5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_metadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("wazuh_agent_version", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("velociraptor_client_version", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_metadata", schema=None) as batch_op:
        batch_op.drop_column("velociraptor_client_version")
        batch_op.drop_column("wazuh_agent_version")

    # ### end Alembic commands ###
