"""Add Client ID and Client Last Seen for Velo Health.

Revision ID: 8b3946f83ac5
Revises: cc9a9e5057ac
Create Date: 2023-07-15 11:32:51.207081

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b3946f83ac5"
down_revision = "cc9a9e5057ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_metadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("client_last_seen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_metadata", schema=None) as batch_op:
        batch_op.drop_column("client_last_seen")
        batch_op.drop_column("client_id")

    # ### end Alembic commands ###
