"""Add Auth fields

Revision ID: 92ef2c136375
Revises: c8c903153246
Create Date: 2023-09-15 10:26:42.478296

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92ef2c136375"
down_revision = "c8c903153246"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("passwordHash", sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column("jwtToken", sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column("tokenExpiry", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("tokenExpiry")
        batch_op.drop_column("jwtToken")
        batch_op.drop_column("passwordHash")

    # ### end Alembic commands ###
