{
 "title": "LANDING",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"text-center\"><img src=\"/public/img/acclamar_logo_black.png\" width=\"50%\" height=\"50%\"></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:40px\"></b>Security Operations Center Portal</b></p>\n<p style=\"font-size:20px\"></b>duane@acclamar.com</b></p>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "## <span style=\"color: orange;\">SOCFortress Windows Installer</span>\n\nSecure your Windows systems with <span style=\"color: purple;\">SOCFortress EDR</span>.\n\nTo install SOCFortress EDR on Windows, follow these steps:\n\n1. Open a PowerShell session with administrative privileges.\n\n2. Copy and paste the following command:\n\n\n```\n$user = 'acclamar'; $pass = 'NTLAyVbaJtWHYGsVJJG9r7DTW'; $pair = \"$($user):$($pass)\"; $encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair)); $basicAuthValue = \"Basic $encodedCreds\"; $Headers = @{ Authorization = $basicAuthValue }; Invoke-RestMethod -Uri 'https://repo.socfortress.co/repository/acclamar/prod/Watchful_Digital_Link_EDR.exe' -Headers $Headers -OutFile \"$env:TMP\\Watchful_Digital_Link_EDR.exe\"; $app ='$env:TMP\\Watchful_Digital_Link_EDR.exe'; $args = \"WAZUHMANAGER='logs.watchfuldigitallink.co'\", \"WAZUHPASSWORD='g0qQkxNIxP2lsRDXoyClmQKYsXhHWwNIaaMOv14c8'\", \"CUSTOMERCODE='Windows_acclamar'\", \"WAZUHREGISTRATIONPORT='20001'\", \"WAZUHMANAGERPORT='20000'\"; Start-Process -FilePath \"$env:TMP\\Watchful_Digital_Link_EDR.exe\" -ArgumentList '/q WAZUHMANAGER=\"logs.watchfuldigitallink.co\" WAZUHPASSWORD=\"g0qQkxNIxP2lsRDXoyClmQKYsXhHWwNIaaMOv14c8\" CUSTOMERCODE=\"Windows_acclamar\" WAZUHREGISTRATIONPORT=\"20001\" WAZUHMANAGERPORT=\"20000\"';\n```"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "options": {
    "content": "## <span style=\"color: orange;\">SOCFortress Linux Installer</span>\n\nSecure your Linux systems with <span style=\"color: purple;\">SOCFortress EDR</span>.\n\nTo install SOCFortress EDR on Linux, follow these steps:\n\n1. Open a shell session as the root user.\n\n2. Copy and paste the following command:\n\n\n```\nif command -v apt >/dev/null 2>&1; then sudo apt update && sudo apt install -y dos2unix; elif command -v yum >/dev/null 2>&1; then sudo yum install -y dos2unix; else echo \"Error: Neither apt nor yum package manager found.\"; exit 1; fi; curl -u acclamar:NTLAyVbaJtWHYGsVJJG9r7DTW -so ~/Client_EDR_install.bash https://repo.socfortress.co/repository/acclamar/installer/Client_EDR_install.bash && dos2unix ~/Client_EDR_install.bash && bash ~/Client_EDR_install.bash -i logs.watchfuldigitallink.co​ 20000 20001 g0qQkxNIxP2lsRDXoyClmQKYsXhHWwNIaaMOv14c8 Linux_acclamar\n```"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "options": {
    "content": "<div class=\"text-left\"><img src=\"/public/img/security.svg\" style=\"width:54px;height:42px;\"></div>\n<p style=\"font-size:20px\"><b>END POINT DETECTION & RESPONSE</b></p>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "options": {
    "content": "<div class=\"text-left\"><img src=\"/public/img/sophos_logo.png\" style=\"width:20%;height:20%;\"></div>\n<p></p>\n<p style=\"font-size:20px\"><b>NETWORK & SYSTEMS LOGS (Sophos)</b></p>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "options": {
    "content": "<p style=\"font-size:20px\"></b>EDR - QUICK STATS (Last 24 Hours)</b></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
   "options": {
    "content": "<p style=\"font-size:20px\"></b>NETWORK LOGS - QUICK STATS (Last 24 Hours)</b></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "EDR ALERTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:>=12 AND !rule_groups:vulnerability-detector",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CRITICAL SYSTEM VULN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_groups:vulnerability-detector AND rule_level:>=12",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACTIVE AGENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "365d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "agent_name", "id": "1", "type": "cardinality" }
     ],
     "query": "rule_level:>2",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DETECTION RULES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "365d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule_description", "id": "1", "type": "cardinality" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SOPHOS ALERTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "priority:alert",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SOPHOS WARNINGS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "priority:Warning",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACTIVE FIREWALLS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "365d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "device_name", "id": "1", "type": "cardinality" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACTIVE FIREWALL RULES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "365d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fw_rule_id", "id": "1", "type": "cardinality" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENT COUNT (Last 24hrs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LOG COUNT (Last 24hrs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "DASHBOARDS & TELEMETRY", "type": "dashlist", "gridPos": { "h": 17, "w": 12, "x": 0, "y": 37 } },
  { "title": "DASHBOARDS & TELEMETRY", "type": "dashlist", "gridPos": { "h": 17, "w": 12, "x": 12, "y": 37 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 54 },
   "options": {
    "content": "<div class=\"text-left\"><img src=\"/public/img/office_365.png\" style=\"width:54px;height:42px;\"></div>\n<p style=\"font-size:20px\"><b>OFFICE 365 LOGS AND EVENTS</b></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 54 },
   "options": {
    "content": "<div class=\"text-left\"><img src=\"/public/img/suricata_logo.png\" style=\"width:54px;height:42px;\"></div>\n<p style=\"font-size:20px\"><b>SURICATA LOGS AND EVENTS</b></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "FAILED AUTHs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office_365_Operation:UserLoginFailed",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AUTHs OUTSIDE US",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office_365_Operation:UserLoggedIn AND !data_office_365_ActorIpAddress_country_code:US",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "PHISHING EMAILS (REPORTED)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office_365_Name:\"Email reported by user as malware or phish\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DLP DETECTIONS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_office_365_Operation:DLPRuleMatch OR data_office_365_Operation:DlpRuleMatch",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "DASHBOARDS & TELEMETRY", "type": "dashlist", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 } },
  {
   "title": "EVENT COUNT (Last 24hrs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "DASHBOARDS & TELEMETRY", "type": "dashlist", "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 70 },
   "options": {
    "content": "<div class=\"text-left\"><img src=\"https://png.pngtree.com/png-vector/20190811/ourmid/pngtree-vector-server-icon-png-image_1660325.jpg\" style=\"width:54px;height:42px;\"></div>\n<p style=\"font-size:20px\"><b>SYSTEM METRICS</b></p>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "SYSTEMS MONITORING DASHBOARDS", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 } }
 ]
}